/* Nationwide map-first interaction; all markers come from checked source reports. */
(function(root){'use strict';
 const $=id=>document.getElementById(id),C=root.SafeBusCore,N=root.SafeBusNationalContract,D=root.SafeBusDataset;
 const esc=x=>String(x??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
 const state={ready:false,map:null,stops:[],station:null,stationData:null,stationError:null,line:null,routeId:null,operatorRef:null,areaData:null,areaError:null,areaBBox:null,revision:0,areaRevision:0,searchRevision:0,busy:false,showStops:true,showBuses:true,traffic:null,trafficEnabled:false,trafficRevision:0,previewRevision:0,markers:new Map(),index:{},searchResults:[]};
 let previewLayer,stopsLayer,busesLayer,selectedLayer,areaTimer,searchTimer,stationController,areaController,searchController,trafficTimer,trafficAgeTimer;
 function toast(message){$('notice').textContent=message;$('notice').hidden=false;clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>$('notice').hidden=true,7000);}
 async function json(url,signal){const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'},signal});if(r.status===429)throw Error('השירות עמוס; ננסה שוב בעוד דקה');if(!r.ok)throw Error('שירות הנתונים אינו זמין כרגע');return r.json();}
 function saveMap(){try{const p=state.map.getCenter();localStorage.setItem('eifo-national-map',JSON.stringify({lat:p.lat,lon:p.lng,zoom:state.map.getZoom()}));}catch{}}
 function viewportStops(){const b=state.map.getBounds();return state.stops.filter(s=>b.contains([s.lat,s.lon]));}
 function renderStops(){stopsLayer.clearLayers();if(!state.showStops)return;const route=state.line&&root.SafeBusApp.state.route?.properties.line===state.line?root.SafeBusApp.state.route:null,codes=route?new Set(route.properties.stopSequence.map(s=>String(s.code))):null,list=viewportStops().filter(s=>!codes||codes.has(s.code)),zoom=state.map.getZoom(),buckets=new Map();
  for(const s of list){if(state.station?.code===s.code)continue;const p=state.map.latLngToContainerPoint([s.lat,s.lon]),cell=zoom>=18?44:zoom>=16?80:zoom>=14?110:zoom>=12?140:150,key=Math.floor(p.x/cell)+':'+Math.floor(p.y/cell);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(s)}
  for(const list of buckets.values()){const s=list[0],count=list.length,lat=list.reduce((sum,x)=>sum+x.lat,0)/count,lon=list.reduce((sum,x)=>sum+x.lon,0)/count;
   const icon=L.divIcon({className:'national-stop-pin',html:count>1?'<span class="stop-cluster">'+count+'</span>':'<span class="national-stop-dot"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="2" width="16" height="14" rx="3" fill="currentColor"/><rect x="7" y="5" width="10" height="5" rx="1" fill="white"/><path d="M12 16v6M8 22h8" stroke="currentColor" stroke-width="2"/><circle cx="8" cy="13" r="1" fill="white"/><circle cx="16" cy="13" r="1" fill="white"/></svg></span>',iconSize:[count>1?36:26,count>1?36:26],iconAnchor:[count>1?18:13,count>1?18:13]});
   L.marker([lat,lon],{icon,title:count>1?count+' תחנות · הגדל לצפייה':s.name+' · '+s.code,keyboard:true}).addTo(stopsLayer).on('click',()=>{if(count===1)return selectStop(s.code);if(zoom<18)return state.map.setView([lat,lon],Math.min(19,zoom+2),{animate:false});L.popup().setLatLng([lat,lon]).setContent('<div class="stop-popup-list">'+list.map(s=>'<button type="button" data-stop-choice="'+esc(s.code)+'">'+esc(s.name)+'<small>תחנה '+esc(s.code)+'</small></button>').join('')+'</div>').openOn(state.map)});
  }
  $('stopCount').textContent=list.length.toLocaleString('he-IL')+(codes?' תחנות מסלול באזור':' תחנות באזור');
 }
 function drawSelected(){selectedLayer.clearLayers();if(!state.station)return;const s=state.station;L.marker([s.lat,s.lon],{icon:L.divIcon({className:'selected-stop-pin',html:'<span></span>',iconSize:[32,32],iconAnchor:[16,16]}),title:s.name+' · התחנה שנבחרה'}).addTo(selectedLayer).bindPopup('<strong>'+esc(s.name)+'</strong><br>תחנה '+esc(s.code));}
 function visibleVehicles(){const rows=state.station?state.stationData?.vehicles||[]:state.areaData?.vehicles||[];return N.vehicles(rows,{bbox:state.station?null:state.areaBBox,stopCode:state.station?.code}).filter(v=>(!state.line||String(v.line)===state.line)&&(!state.routeId||String(v.routeId)===state.routeId)&&(!state.operatorRef||String(v.operatorRef)===state.operatorRef));}
 function renderBuses(){const list=state.showBuses?visibleVehicles():[],visible=new Set();for(const v of list){const meta=N.routeMeta(v,state.stationData?.routes,state.index);if(!v.line&&meta)v.line=meta.line;const age=C.gpsAge(v.observed_at),label=v.line?'קו '+v.line:'רכב מדווח',html=root.SafeBusExperience.marker(v,v.line||'?',null),icon=L.divIcon({className:'bus-pin',html,iconSize:[44,44],iconAnchor:[22,22]});
   const destination=meta?.headsign||'לא זמין במקור',speed=v.reportedSpeedKmh===null?'לא דווחה':esc(v.reportedSpeedKmh)+' קמ״ש';
   const stamp=value=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('he-IL'):'לא זמין במקור';
   const popup='<div class="bus-report"><strong>'+esc(label)+'</strong><dl><dt>'+(v.directionVerified?'יעד הנסיעה':'יעד המסלול')+'</dt><dd>'+esc(destination)+'</dd><dt>מהירות מדווחת</dt><dd>'+speed+'</dd></dl><small data-report-age>דיווח לפני '+esc(C.ageText(age))+' · רכב '+esc(v.vehicleRef)+'</small><p>מיקום ומהירות מדיווח המקור; אין זמן מדידת GPS עצמאי. הפרטים נשארים כתצפית זו בזמן הקריאה.</p>'+(v.directionVerified?'':'<p>כיוון הנסיעה לא אומת; יעד הנסיעה וזמן ההגעה אינם מאומתים.</p>')+'<details class="bus-source"><summary>מקור וזמני הדיווח</summary><dl><dt>מפעיל במקור</dt><dd>'+esc(v.operatorRef)+'</dd><dt>מסלול במקור</dt><dd>'+esc(v.routeId||'לא זמין')+'</dd><dt>נסיעה במקור</dt><dd>'+esc(v.tripId||'לא זמינה')+'</dd><dt>ספק</dt><dd><bdi>'+esc(v.source||'לא זמין')+'</bdi></dd><dt>זמן דיווח</dt><dd>'+esc(stamp(v.sourceObservedAt||v.observed_at))+'</dd><dt>תגובת המקור</dt><dd>'+esc(stamp(v.sourceResponseAt))+'</dd><dt>צילום הארכיון</dt><dd>'+esc(stamp(v.snapshotAt))+'</dd></dl></details><div class="bus-actions">'+(meta?.line?'<button type="button" data-bus-route="'+esc(v.routeId)+'" data-bus-operator="'+esc(v.operatorRef)+'" data-bus-line="'+esc(meta.line)+'">הצג מסלול GTFS</button>':'')+'<button type="button" class="archive-link" data-vehicle-history="'+esc(v.vehicleRef)+'" data-operator-ref="'+esc(v.operatorRef)+'">היסטוריית הרכב</button></div></div>';
   visible.add(v.id);if(state.markers.has(v.id)){
    const m=state.markers.get(v.id),snapshotFresh=N.fresh(m._reportAt,Date.now());
    if(m.isPopupOpen()&&snapshotFresh){const small=m.getPopup().getElement()?.querySelector('[data-report-age]');if(small)small.textContent='דיווח לפני '+C.ageText(C.gpsAge(m._reportAt))+' · רכב '+v.vehicleRef;}
    else {if(m.isPopupOpen())m.closePopup();m._reportAt=v.sourceObservedAt;m.setLatLng([v.lat,v.lon]).setIcon(icon).setPopupContent(popup);}
   }else {
    const m=L.marker([v.lat,v.lon],{icon,title:label+' · דיווח לפני '+C.ageText(age),zIndexOffset:300}).addTo(busesLayer).bindPopup(popup,{autoPanPaddingTopLeft:[15,170],autoPanPaddingBottomRight:[15,120]});
    m._reportAt=v.sourceObservedAt;m.on('popupclose',()=>{queueMicrotask(renderBuses)});state.markers.set(v.id,m);
   }
  }for(const [id,m]of state.markers)if(!visible.has(id)){busesLayer.removeLayer(m);state.markers.delete(id)}
  $('nationalBusCount').textContent=list.length?list.length+' אוטובוסים מדווחים':state.busy?'בודק דיווחי אוטובוסים…':state.stationError||state.areaError?'הדיווחים אינם זמינים כרגע':!state.station&&(state.map.getZoom()<11||!state.areaBBox)?'התמקד באזור להצגת אוטובוסים':'אין דיווחי מיקום עדכניים';$('nationalBusCount').classList.toggle('has-buses',list.length>0);
  $('nationalFocus').disabled=!list.length;
 }
 function renderArrivals(){const output=$('stationArrivals');output.replaceChildren();if(!state.station)return;const data=state.stationData,rows=(data?.arrivals||[]).filter(r=>N.fresh(r.sourceObservedAt,Date.now())&&N.fresh(r.sourceResponseAt,Date.now())&&Date.parse(r.reportedArrivalAt)>=Date.now()-60000&&(!state.line||String(r.line)===state.line)&&(!state.routeId||String(r.routeId)===state.routeId)&&(!state.operatorRef||String(r.operatorRef)===state.operatorRef));
  if(!rows.length){const p=document.createElement('p');p.className='station-empty';p.textContent=state.busy?'בודק זמני הגעה לכל הקווים…':state.stationError?'לא ניתן לקבל כרגע זמני הגעה. ננסה שוב אוטומטית.':'אין כרגע תחזיות עדכניות לקווים שבחרת. זה אינו מעיד שהשירות הופסק.';output.append(p);return;}
  for(const a of rows.slice(0,14)){const row=document.createElement('button');row.type='button';row.className='station-arrival';const dest=data.routes.find(r=>String(r.routeId)===String(a.routeId)&&String(r.operatorRef)===String(a.operatorRef))?.headsign||'כיוון לפי המסלול';row.innerHTML='<span class="line-badge">'+esc(a.line)+'</span><span class="arrival-destination">'+esc(dest)+'<small>תחזית מדווחת</small></span><strong>'+Math.max(1,Math.ceil((Date.parse(a.reportedArrivalAt)-Date.now())/60000))+'<small>דק׳</small></strong>';row.onclick=()=>selectLine(String(a.line),String(a.routeId),String(a.operatorRef));output.append(row)}
 }
 function renderLineChoices(){const output=$('stationLines');output.replaceChildren();const lines=state.station?D.linesAt(state.station.code).sort((a,b)=>a.localeCompare(b,'he',{numeric:true})):[],select=$('stationLineSelect');select.replaceChildren();for(const line of [null,...lines]){const option=document.createElement('option');option.value=line||'';option.textContent=line?'קו '+line:'כל הקווים';select.append(option)}select.value=state.line||'';const quick=[...new Set([state.line,...(state.stationData?.arrivals||[]).map(a=>String(a.line)),...lines].filter(Boolean))].slice(0,5);for(const line of quick){const b=document.createElement('button');b.type='button';b.className='line-choice';b.textContent=line||'כל הקווים';b.setAttribute('aria-pressed',String(state.line===line));b.onclick=()=>selectLine(line);output.append(b)}}
 async function selectLine(line,routeId=null,operatorRef=null){clearPreview();const revision=state.revision,token=state.lineRevision=(state.lineRevision||0)+1;routeId=routeId||state.stationData?.arrivals.find(a=>String(a.line)===line)?.routeId||state.stationData?.vehicles.find(v=>String(v.line)===line)?.routeId||null;state.line=line;state.routeId=routeId;state.operatorRef=operatorRef;renderLineChoices();renderArrivals();renderBuses();if(!line){root.SafeBusApp.clearSelection();$('directionWrap').hidden=true;renderStops();return;}
  $('line').value=line;$('stop').value=state.station.code;await root.SafeBusApp.applySelection();if(!state.station||state.line!==line||state.revision!==revision||state.lineRevision!==token)return;
  if(routeId){const idx=root.SafeBusApp.state.allRoutes.findIndex(r=>String(r.properties.routeId)===routeId&&(!operatorRef||String(r.properties.agencyId)===operatorRef));if(idx<0){root.SafeBusApp.clearSelection();state.routeId=routeId;$('directionWrap').hidden=true;toast('לא נמצא מסלול GTFS מתאים לזהות המקור. לא יוצג תוואי משוער.');renderStops();return;}if(idx>=0){$('direction').value=String(idx);$('direction').dispatchEvent(new Event('change'))}}
  if(root.SafeBusApp.state.stopMarker)state.map.removeLayer(root.SafeBusApp.state.stopMarker);const route=root.SafeBusApp.state.route;state.routeId=route?String(route.properties.routeId):null;state.operatorRef=route?String(route.properties.agencyId):null;renderArrivals();renderBuses();renderStops();
 }
 async function selectStop(code){clearPreview();const s=state.stops.find(x=>x.code===String(code));if(!s)return;state.searchRevision++;searchController?.abort();$('searchSubmit').disabled=false;stationController?.abort();areaController?.abort();state.areaRevision++;state.revision++;state.station=s;state.stationData=null;state.stationError=null;state.line=null;state.routeId=null;state.operatorRef=null;root.SafeBusApp.clearSelection();$('stop').value=s.code;$('placeSearch').value=s.name;$('stationTitle').textContent=s.name;$('stationCode').textContent='תחנה '+s.code;$('areaCoverage').textContent='אוטובוסים המשויכים לתחנה '+s.code;$('stationDock').hidden=false;$('stationDock').classList.remove('minimized');$('stationBody').hidden=false;$('dockToggle').setAttribute('aria-expanded','true');$('directionWrap').hidden=true;hideSearch();drawSelected();renderLineChoices();state.map.setView([s.lat,s.lon],Math.max(16,state.map.getZoom()),{animate:false});await refreshStation();}
 function closeStation(){clearPreview();stationController?.abort();state.revision++;state.station=null;state.stationData=null;state.stationError=null;state.line=null;state.routeId=null;state.operatorRef=null;root.SafeBusApp.clearSelection();$('stationDock').hidden=true;drawSelected();renderBuses();refreshArea();}
 async function refreshStation(){if(!state.station)return;const revision=state.revision,code=state.station.code;stationController?.abort();stationController=new AbortController();state.busy=true;renderArrivals();renderBuses();$('stationRefresh').disabled=true;
  try{const raw=await json('./api/national?kind=station&stopCode='+encodeURIComponent(code),stationController.signal);if(revision!==state.revision)return;state.stationData=N.station(raw,code);state.stationError=null;renderLineChoices();$('stationUpdated').textContent=N.fresh(raw.sourceResponseAt,Date.now())?'תגובת מקור '+new Date(raw.sourceResponseAt).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}):'זמן המקור חסר או פג';$('stationCoverage').textContent=raw.partial?'חלק מהקווים לא זמינים כרגע':D.linesAt(code).length+' קווים עוברים בתחנה';}
  catch(e){if(e.name==='AbortError'||revision!==state.revision)return;state.stationError=e.message;state.stationData=null;$('stationUpdated').textContent='אין תגובת מקור עדכנית';}
  finally{if(revision===state.revision){state.busy=false;$('stationRefresh').disabled=false;renderArrivals();renderBuses()}}
 }
 function currentBBox(){const b=state.map.getBounds();return [Math.max(34,b.getWest()),Math.max(29,b.getSouth()),Math.min(36,b.getEast()),Math.min(34,b.getNorth())].map(n=>Number(n.toFixed(5)))}
 async function refreshArea(){if(state.station||!state.showBuses)return;const bbox=currentBBox();if(bbox[2]-bbox[0]>.4||bbox[3]-bbox[1]>.4||bbox[0]>=bbox[2]||bbox[1]>=bbox[3]){areaController?.abort();state.areaRevision++;state.areaData=null;state.busy=false;state.areaError=null;$('areaCoverage').textContent='חפש מקום או הגדל את המפה להצגת אוטובוסים';renderBuses();return;}
  const revision=++state.areaRevision;areaController?.abort();areaController=new AbortController();state.busy=true;state.areaError=null;state.areaBBox=bbox;renderBuses();$('areaCoverage').textContent='בודק דיווחים באזור המוצג';
  try{const raw=await json('./api/national?kind=area&bbox='+bbox.join(','),areaController.signal);if(revision!==state.areaRevision||state.station)return;state.areaData=N.area(raw,bbox);$('areaCoverage').textContent=raw.coverage==='nearby-stop-reports'?'דיווחים מ־'+raw.sampledStopCodes.length+' תחנות סמוכות · הכיסוי חלקי':raw.truncated?'דיווחים באזור · רשימת המקור חלקית':'דיווחים באזור המוצג';}
  catch(e){if(e.name==='AbortError'||revision!==state.areaRevision)return;state.areaError=e.message;state.areaData=null;$('areaCoverage').textContent='אין כרגע חיבור למיקומים באזור';}
  finally{if(revision===state.areaRevision&&!state.station){state.busy=false;renderBuses()}}
 }
 function hideSearch(){clearTimeout(searchTimer);$('searchResults').hidden=true;$('placeSearch').setAttribute('aria-expanded','false')}
 function showResults(local,places=[],note=''){const list=$('searchResults');list.replaceChildren();state.searchResults=[];const add=(item,label,detail,action)=>{const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.innerHTML='<span>'+esc(label)+'</span><small>'+esc(detail)+'</small>';b.onclick=action;li.append(b);list.append(li);state.searchResults.push(b)};
  for(const p of places)add(p,p.name,'כתובת או מקום · OpenStreetMap',()=>{closeStation();state.map.setView([p.lat,p.lon],16,{animate:false});$('placeSearch').value=p.name;hideSearch()});for(const s of local)add(s,s.name,'תחנה '+s.code,()=>selectStop(s.code));
  if(note){const li=document.createElement('li');li.className='search-note';li.textContent=note;list.append(li)}list.hidden=!list.children.length;$('placeSearch').setAttribute('aria-expanded',String(!list.hidden));
 }
 function localSearch(){const text=$('placeSearch').value.trim();const c=state.map.getCenter();return N.stopSearch(state.stops,text,{lat:c.lat,lon:c.lng})}
 async function search(event){event?.preventDefault();const q=$('placeSearch').value.trim();if(q.length<2){toast('הקלד כתובת, מקום, שם תחנה או מספר תחנה');return;}
  const local=localSearch();if(/^\d{3,7}$/.test(q)&&local.some(s=>s.code===q)){selectStop(q);return;}
  const revision=++state.searchRevision;searchController?.abort();searchController=new AbortController();$('searchSubmit').disabled=true;showResults(local,[],'מחפש כתובות ומקומות…');
  try{const raw=await json('./api/search?q='+encodeURIComponent(q),searchController.signal);if(revision!==state.searchRevision)return;showResults(local,raw.places||[],raw.places?.length?'':'לא נמצאה כתובת. נסה שם רחוב ועיר, או בחר תחנה.');}
  catch(e){if(e.name==='AbortError'||revision!==state.searchRevision)return;showResults(local,[],'חיפוש הכתובות אינו זמין כרגע; חיפוש תחנות עדיין עובד.');}
  finally{if(revision===state.searchRevision)$('searchSubmit').disabled=false}
 }

 function clearPreview(){state.previewRevision++;previewLayer?.clearLayers();if($('routePreview'))$('routePreview').hidden=true;}
 async function previewRoute(line,routeId,operatorRef){
  if(state.station)return selectLine(line,routeId,operatorRef);
  clearPreview();const revision=state.previewRevision;
  try{
   const routes=await D.routesFor(line),match=routes.filter(f=>String(f.properties.routeId)===routeId&&String(f.properties.agencyId)===operatorRef);
   if(revision!==state.previewRevision)return;
   if(!match.length){toast('אין תוואי GTFS שמתאים למפעיל ולמסלול המדווחים.');return;}
   const f=match[0],collection={type:'FeatureCollection',features:match};L.geoJSON(collection,{style:feature=>({color:'#1765d7',weight:6,opacity:.85,dashArray:match.length>1||feature.properties.suspect?'8 7':null})}).addTo(previewLayer);
   $('routePreviewTitle').textContent=match.length===1?'קו '+line+' · '+f.properties.origin+' ← '+f.properties.destination:'קו '+line+' · '+match.length+' חלופות מסלול GTFS';
   $('routePreviewNote').textContent='תוואי GTFS · כיוון נסיעת הרכב לא אומת'+(match.length>1?' · אין שיוך לחלופה מסוימת':'')+(f.properties.suspect?' · חריגה בקצה התוואי במקור':'');
   $('routePreview').hidden=false;
   state.map.closePopup();state.map.fitBounds(L.geoJSON(collection).getBounds(),{padding:[35,170],maxZoom:16,animate:false});
  }catch{if(revision===state.previewRevision)toast('לא ניתן לטעון כרגע את מסלול המקור.');}
 }
 function stopTraffic(message=''){
  state.trafficRevision++;state.trafficEnabled=false;clearInterval(trafficTimer);clearTimeout(trafficAgeTimer);
  if(state.traffic)state.map.removeLayer(state.traffic);state.traffic=null;
  $('trafficLayerToggle').setAttribute('aria-pressed','false');$('trafficLegend').hidden=true;
  if(message)toast(message);
 }
 async function toggleTraffic(){
  if(state.trafficEnabled){stopTraffic();return;}
  const button=$('trafficLayerToggle'),revision=++state.trafficRevision;button.disabled=true;
  try{
   const config=await json('./api/traffic?kind=status');if(revision!==state.trafficRevision)return;
   if(!config.available){toast('שכבת הפקקים ממתינה לחיבור TomTom. הקישור נמצא בהגדרות ← חיבורים ושירותים.');return;}
   if(config.state==='quota-exhausted'){toast('מכסת ספק התנועה נוצלה. לא תוצג שכבת פקקים ישנה.');return;}
   state.trafficEnabled=true;button.setAttribute('aria-pressed','true');
   const expire=code=>{if(revision!==state.trafficRevision)return;stopTraffic(code==='TRAFFIC_QUOTA_EXHAUSTED'?'מכסת ספק התנועה נוצלה; צבעי הפקקים הוסרו.':code==='TRAFFIC_EXPIRED'?'תוקף נתוני הפקקים פג; צבעי התנועה הוסרו.':'נתוני הפקקים אינם זמינים כרגע; צבעי התנועה הוסרו.');};
   state.traffic=root.SafeBusTrafficTiles.create({onFailure:expire,onClock:clock=>{
    if(revision!==state.trafficRevision)return;clearTimeout(trafficAgeTimer);$('trafficLegend').hidden=false;
    $('trafficClock').textContent='תגובת ספק '+new Date(clock.originatedAt).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit',second:'2-digit'})+' · אינו זמן מדידת הכביש';
   }});
   state.traffic.addTo(state.map);trafficAgeTimer=setTimeout(()=>expire('TRAFFIC_UNAVAILABLE'),12000);
   trafficTimer=setInterval(()=>{if(revision===state.trafficRevision&&state.traffic&&!document.hidden){$('trafficLegend').hidden=true;state.traffic.redraw();trafficAgeTimer=setTimeout(()=>expire('TRAFFIC_UNAVAILABLE'),12000);}},60000);
  }catch{stopTraffic('לא ניתן לקבל כרגע נתוני פקקים.');}finally{button.disabled=false}
 }
 function init(){if(state.ready||!root.SafeBusApp?.state.map)return;state.ready=true;state.map=root.SafeBusApp.state.map;$('map').addEventListener('click',e=>{const b=e.target.closest?.('[data-stop-choice]');if(b)selectStop(b.dataset.stopChoice);const route=e.target.closest?.('[data-bus-route]');if(route)previewRoute(route.dataset.busLine,route.dataset.busRoute,route.dataset.busOperator)});state.map.removeLayer(root.SafeBusApp.state.vehicleLayer);state.map.createPane('trafficPane');state.map.getPane('trafficPane').style.zIndex=350;state.map.getPane('trafficPane').style.pointerEvents='none';stopsLayer=L.layerGroup().addTo(state.map);busesLayer=L.layerGroup().addTo(state.map);selectedLayer=L.layerGroup().addTo(state.map);previewLayer=L.layerGroup().addTo(state.map);$('closeRoutePreview').onclick=clearPreview;$('countryView').onclick=()=>{closeStation();state.map.fitBounds(L.latLngBounds(state.stops.map(s=>[s.lat,s.lon])),{padding:[20,110],animate:false});};
  state.stops=Object.entries(D.catalog().stops).filter(([code,s])=>D.linesAt(code).length&&C.validCoord(s[0],s[1])).map(([code,s])=>({code,lat:s[0],lon:s[1],name:String(s[2]),search:N.fold(s[2]+' '+code)}));
  try{const p=JSON.parse(localStorage.getItem('eifo-national-map')||'null');if(p&&C.validCoord(p.lat,p.lon)&&p.zoom>=7&&p.zoom<=19)state.map.setView([p.lat,p.lon],p.zoom,{animate:false})}catch{}
  fetch('./data/routes-index.json').then(r=>r.ok?r.json():null).then(data=>{if(data?.catalogVersion===D.version()){state.index=data.routes;renderBuses()}}).catch(()=>{});
  $('searchForm').onsubmit=search;$('placeSearch').oninput=()=>{state.searchRevision++;searchController?.abort();$('searchSubmit').disabled=false;clearTimeout(searchTimer);searchTimer=setTimeout(()=>showResults(localSearch(),[],$('placeSearch').value.trim().length>=2?'לחיפוש כתובת, לחץ חיפוש או Enter':''),160)};
  $('placeSearch').onkeydown=e=>{if(e.key==='Escape')hideSearch();if(e.key==='ArrowDown'&&state.searchResults.length){e.preventDefault();state.searchResults[0].focus()}};$('searchResults').onkeydown=e=>{const i=state.searchResults.indexOf(document.activeElement);if(e.key==='Escape'){hideSearch();$('placeSearch').focus()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();state.searchResults[(i+(e.key==='ArrowDown'?1:-1)+state.searchResults.length)%state.searchResults.length]?.focus()}};
  $('stationLineSelect').onchange=()=>selectLine($('stationLineSelect').value||null);$('closeStation').onclick=closeStation;$('stationRefresh').onclick=refreshStation;$('dockToggle').onclick=()=>{const hide=!$('stationBody').hidden;$('stationBody').hidden=hide;$('stationDock').classList.toggle('minimized',hide);$('dockToggle').setAttribute('aria-expanded',String(!hide))};
  $('stationsToggle').onclick=()=>{state.showStops=!state.showStops;$('stationsToggle').setAttribute('aria-pressed',String(state.showStops));renderStops()};$('busesToggle').onclick=()=>{state.showBuses=!state.showBuses;$('busesToggle').setAttribute('aria-pressed',String(state.showBuses));renderBuses();if(state.showBuses&&!state.station)refreshArea()};$('trafficLayerToggle').onclick=toggleTraffic;
  $('nationalFocus').onclick=()=>{const list=visibleVehicles();if(list.length){const bounds=L.latLngBounds(list.map(v=>[v.lat,v.lon]));if(state.station)bounds.extend([state.station.lat,state.station.lon]);state.map.fitBounds(bounds.pad(.15),{maxZoom:17,animate:false})}};
  $('myLocation').onclick=()=>{if(!navigator.geolocation){toast('הדפדפן אינו תומך בקבלת מיקום');return;}navigator.geolocation.getCurrentPosition(p=>{if(!C.validCoord(p.coords.latitude,p.coords.longitude)){toast('המיקום מחוץ לתחום המפה הארצית');return;}closeStation();state.map.setView([p.coords.latitude,p.coords.longitude],16,{animate:false})},()=>toast('לא התקבל מיקום. אפשר לחפש כתובת או להזיז את המפה.'),{enableHighAccuracy:false,timeout:10000,maximumAge:60000})};
  state.map.on('autopanstart',()=>{state.popupPanning=true});state.map.on('movestart',()=>{if(!state.station&&!state.popupPanning){areaController?.abort();state.areaRevision++;state.areaData=null;state.busy=false;renderBuses()}});state.map.on('moveend',()=>{renderStops();saveMap();if(state.popupPanning){state.popupPanning=false;return;}clearTimeout(areaTimer);areaTimer=setTimeout(refreshArea,550)});state.map.on('click',hideSearch);
  $('direction').addEventListener('change',()=>{if(!state.station||!state.line)return;state.routeId=String(root.SafeBusApp.state.allRoutes[Number($('direction').value)]?.properties.routeId||'');state.operatorRef=String(root.SafeBusApp.state.allRoutes[Number($('direction').value)]?.properties.agencyId||'');if(root.SafeBusApp.state.stopMarker)state.map.removeLayer(root.SafeBusApp.state.stopMarker);renderArrivals();renderBuses();renderStops()});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(state.trafficEnabled)stopTraffic('חזרת למפה; הפעל פקקים לקבלת נתונים חדשים.');state.station?refreshStation():refreshArea()}});setInterval(()=>{if(!document.hidden)state.station?refreshStation():refreshArea()},60000);setInterval(()=>{if(state.ready){renderArrivals();renderBuses()}},15000);renderStops();refreshArea();const params=new URL(location.href).searchParams,a=Number(params.get('lat')),b=Number(params.get('lon'));if(params.has('lat')&&params.has('lon')&&C.validCoord(a,b))state.map.setView([a,b],15,{animate:false});if(params.get('traffic')==='1')toggleTraffic();$('catalogStatus').textContent=state.stops.length.toLocaleString('he-IL')+' תחנות · '+D.allLines().length+' מספרי קווים בכל הארץ';
 }
 async function services(){const status=$('trafficConnectionStatus');if(!status)return;status.textContent='בודק חיבור תנועה…';try{const config=await json('./api/traffic?kind=status');status.textContent=config.available?'החיבור מוגדר; נתוני התנועה נבדקים בהפעלת השכבה':'ממתין לחיבור חשבון TomTom בידי בעל האתר';$('trafficAccountLink').hidden=!!config.available;}catch{status.textContent='לא ניתן לבדוק כרגע את חיבור התנועה';$('trafficAccountLink').hidden=false;}}
 root.SafeBusNational={state,init,selectStop,selectLine,closeStation,refreshArea,refreshStation,renderStops,renderBuses,search,toggleTraffic,services,previewRoute,stopTraffic};
})(window);
