/* Nationwide map-first interaction; all markers come from checked source reports. */
(function(root){'use strict';
 const $=id=>document.getElementById(id),C=root.SafeBusCore,N=root.SafeBusNationalContract,D=root.SafeBusDataset;
 const esc=x=>String(x??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
 const state={ready:false,map:null,stops:[],station:null,stationData:null,stationError:null,line:null,routeId:null,operatorRef:null,areaData:null,areaError:null,areaBBox:null,revision:0,areaRevision:0,searchRevision:0,busy:false,showStops:true,showBuses:true,traffic:null,trafficEnabled:false,trafficRevision:0,trafficStatus:'unknown',trafficWanted:true,trafficClock:null,previewRevision:0,previewRoutes:[],previewFilter:null,openVehicleId:null,markers:new Map(),index:{},indexVersion:null,searchResults:[],searchHistory:[]};
 let previewLayer,stopsLayer,busesLayer,selectedLayer,areaTimer,busExpiryTimer,arrivalExpiryTimer,searchTimer,stationController,areaController,searchController,trafficTimer,trafficAgeTimer;
 function coverage(text,partial=false){$('areaCoverage').textContent=text;$('areaCoverage').hidden=!partial;}
 function toast(message){$('notice').textContent=message;$('notice').hidden=false;clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>$('notice').hidden=true,4500);}
 async function json(url,signal){const timeout=AbortSignal.timeout(16000);let r;try{r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'},signal:signal?AbortSignal.any([signal,timeout]):timeout});}catch(e){if(e.name==='TimeoutError')throw Error('השירות לא השיב בזמן');throw e;}if(r.status===429)throw Error('השירות עמוס; ננסה שוב בעוד דקה');if(!r.ok)throw Error('שירות הנתונים אינו זמין כרגע');return r.json();}

 function saveSearch(item){state.searchHistory=N.rememberSearch(state.searchHistory,item);try{localStorage.setItem('eifo-search-history',JSON.stringify(state.searchHistory))}catch{}}
 function choosePlace(p){saveSearch({kind:'place',label:p.name,lat:p.lat,lon:p.lon});closeStation();state.map.setView([p.lat,p.lon],16,{animate:false});$('placeSearch').value=p.name;hideSearch();}
 function showHistory(){const list=$('searchResults');list.replaceChildren();state.searchResults=[];
  if(!state.searchHistory.length){hideSearch();return;}
  const header=document.createElement('li');header.className='search-history-head';const text=document.createElement('span');text.textContent='אחרונים';const clear=document.createElement('button');clear.type='button';clear.textContent='ניקוי';clear.setAttribute('aria-label','ניקוי היסטוריית חיפושים');clear.onclick=()=>{state.searchHistory=[];try{localStorage.removeItem('eifo-search-history')}catch{}hideSearch();$('placeSearch').focus()};header.append(text,clear);list.append(header);
  for(const item of state.searchHistory){const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.className='recent-search';b.innerHTML='<span>'+esc(item.label)+'</span><small>'+(item.kind==='stop'?'תחנה '+esc(item.code):item.kind==='place'?'מקום':'חיפוש')+'</small>';b.onclick=()=>{if(item.kind==='stop'){if(!state.stops.some(s=>s.code===item.code)){toast('התחנה חסרה במאגר הנוכחי');return;}selectStop(item.code);}else if(item.kind==='place')choosePlace({name:item.label,lat:item.lat,lon:item.lon});else{$('placeSearch').value=item.label;search();}};li.append(b);list.append(li);state.searchResults.push(b);}
  list.hidden=false;$('placeSearch').setAttribute('aria-expanded','true');
 }
 function catalogStops(){return Object.entries(D.catalog().stops).filter(([code,s])=>D.linesAt(code).length&&C.validCoord(s[0],s[1])).map(([code,s])=>({code,lat:s[0],lon:s[1],name:String(s[2]),search:N.fold(s[2]+' '+code)}));}

 function saveMap(){try{const p=state.map.getCenter();localStorage.setItem('eifo-national-map',JSON.stringify({lat:p.lat,lon:p.lng,zoom:state.map.getZoom()}));}catch{}}
 function viewportStops(){const b=state.map.getBounds();return state.stops.filter(s=>b.contains([s.lat,s.lon]));}
 function renderStops(){stopsLayer.clearLayers();const zoom=state.map.getZoom();$('stopCount').hidden=!state.showStops||zoom<15;if(!state.showStops||zoom<15)return;const route=state.line&&root.SafeBusApp.state.route?.properties.line===state.line?root.SafeBusApp.state.route:null,routes=state.previewRoutes.length?state.previewRoutes:route?[route]:[],codes=routes.length?new Set(routes.flatMap(r=>r.properties.stopSequence.map(s=>String(s.code)))):null,list=viewportStops().filter(s=>!codes||codes.has(s.code)),buckets=new Map();
  for(const s of list){if(state.station?.code===s.code)continue;const p=state.map.latLngToContainerPoint([s.lat,s.lon]),cell=zoom>=18?44:zoom>=17?80:110,key=Math.floor(p.x/cell)+':'+Math.floor(p.y/cell);if(!buckets.has(key))buckets.set(key,[]);buckets.get(key).push(s)}
  for(const list of buckets.values()){const s=list[0],count=list.length,lat=list.reduce((sum,x)=>sum+x.lat,0)/count,lon=list.reduce((sum,x)=>sum+x.lon,0)/count;
   const icon=L.divIcon({className:'national-stop-pin',html:count>1?'<span class="stop-cluster"><svg viewBox="0 0 16 16" aria-hidden="true"><circle cx="5" cy="5" r="1.4"/><circle cx="11" cy="5" r="1.4"/><circle cx="8" cy="10" r="1.4"/></svg></span>':'<span class="national-stop-dot"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="2" width="16" height="14" rx="3" fill="currentColor"/><rect x="7" y="5" width="10" height="5" rx="1" fill="white"/><path d="M12 16v6M8 22h8" stroke="currentColor" stroke-width="2"/><circle cx="8" cy="13" r="1" fill="white"/><circle cx="16" cy="13" r="1" fill="white"/></svg></span>',iconSize:[24,24],iconAnchor:[12,12]});
   L.marker([lat,lon],{icon,title:count>1?count+' תחנות · הגדל לצפייה':s.name+' · '+s.code,keyboard:true}).addTo(stopsLayer).on('click',()=>{if(count===1)return selectStop(s.code);if(zoom<18)return state.map.setView([lat,lon],Math.min(19,zoom+2),{animate:false});L.popup().setLatLng([lat,lon]).setContent('<div class="stop-popup-list">'+list.map(s=>'<button type="button" data-stop-choice="'+esc(s.code)+'">'+esc(s.name)+'<small>תחנה '+esc(s.code)+'</small></button>').join('')+'</div>').openOn(state.map)});
  }
  $('stopCount').textContent=list.length.toLocaleString('he-IL')+(codes?' תחנות מסלול באזור':' תחנות באזור');
 }
 function drawSelected(){selectedLayer.clearLayers();if(!state.station)return;const s=state.station;L.marker([s.lat,s.lon],{icon:L.divIcon({className:'selected-stop-pin',html:'<span></span>',iconSize:[32,32],iconAnchor:[16,16]}),title:s.name+' · התחנה שנבחרה'}).addTo(selectedLayer).bindPopup('<strong>'+esc(s.name)+'</strong><br>תחנה '+esc(s.code));}
 function routeVisible(v){const selection=state.previewFilter||state;return (!selection.line||String(v.line)===selection.line)&&(!selection.routeId||String(v.routeId)===selection.routeId)&&(!selection.operatorRef||String(v.operatorRef)===selection.operatorRef);}
 function visibleVehicles(){const rows=state.station?state.stationData?.vehicles||[]:state.areaData?.vehicles||[],bbox=state.station?null:state.areaBBox;return N.vehicles(rows,{stopCode:state.station?.code}).filter(v=>!bbox||v.id===state.openVehicleId||(v.lon>=bbox[0]&&v.lon<=bbox[2]&&v.lat>=bbox[1]&&v.lat<=bbox[3])).map(v=>{const meta=N.routeMeta(v,state.stationData?.routes,state.indexVersion===D.version()?state.index:{});return !v.line&&meta?.line?{...v,line:meta.line}:v}).filter(routeVisible);}
 function busReport(){
  const report=document.createElement('div');report.className='bus-report';
  report.innerHTML='<strong data-bus-label></strong><div class="bus-destination"><small data-destination-label></small><span data-bus-destination></span></div><div class="bus-reading"><span data-bus-speed></span><small data-report-age></small></div><div class="bus-actions"><button type="button" data-bus-route>המסלול</button><button type="button" class="archive-link" data-vehicle-history>נסיעות קודמות</button></div><details class="bus-source"><summary>פרטי מקור</summary><dl data-source-fields></dl><p>מיקום ומהירות מדיווח המקור; זמן GPS עצמאי חסר.</p></details>';
  return report;
 }
 function updateBusReport(report,v,meta){
  const text=(selector,value)=>{const e=report.querySelector(selector);if(e.textContent!==value)e.textContent=value;},stamp=value=>Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('he-IL'):'חסר';
  text('[data-bus-label]',v.line?'קו '+v.line:'רכב מדווח');text('[data-destination-label]',v.directionVerified?'יעד':'יעד מסלול');text('[data-bus-destination]',meta?.headsign||'יעד חסר');text('[data-bus-speed]',v.reportedSpeedKmh===null?'מהירות חסרה':v.reportedSpeedKmh+' קמ״ש');text('[data-report-age]','לפני '+C.ageText(C.gpsAge(v.sourceObservedAt)));
  const route=report.querySelector('[data-bus-route]');route.hidden=!meta?.line;route.dataset.busRoute=String(v.routeId);route.dataset.busOperator=String(v.operatorRef);route.dataset.busLine=meta?.line||'';
  const history=report.querySelector('[data-vehicle-history]');history.dataset.vehicleHistory=String(v.vehicleRef);history.dataset.operatorRef=String(v.operatorRef);
  const fields=[['רכב',v.vehicleRef],['מפעיל במקור',v.operatorRef],['מסלול במקור',v.routeId||'חסר'],['נסיעה במקור',v.tripId||'חסרה'],['ספק',v.source||'חסר'],['זמן דיווח',stamp(v.sourceObservedAt)],['תגובת המקור',stamp(v.sourceResponseAt)],['צילום הארכיון',stamp(v.snapshotAt)]],html=fields.map(([label,value])=>'<dt>'+esc(label)+'</dt><dd><bdi>'+esc(value)+'</bdi></dd>').join('');
  const source=report.querySelector('[data-source-fields]');if(source.innerHTML!==html)source.innerHTML=html;
 }
 function updateOpenPopup(m){const report=m._reportElement,focus=document.activeElement,restore=report.contains(focus),scroll=report.scrollTop;m.getPopup().update();report.scrollTop=scroll;if(restore&&focus.isConnected)focus.focus({preventScroll:true});}
 function renderBuses(){const list=state.showBuses?visibleVehicles():[],visible=new Set();for(const v of list){const meta=N.routeMeta(v,state.stationData?.routes,state.indexVersion===D.version()?state.index:{}),label=v.line?'קו '+v.line:'רכב מדווח',html=root.SafeBusExperience.marker(v,v.line||'?',null),icon=L.divIcon({className:'bus-pin',html,iconSize:[44,44],iconAnchor:[22,22]}),destination=meta?.headsign||'חסר',title=label+(destination==='חסר'?'':(v.directionVerified?' · ל־':' · מסלול ל־')+destination);
   visible.add(v.id);let m=state.markers.get(v.id);
   if(!m){
    const report=busReport();updateBusReport(report,v,meta);
    m=L.marker([v.lat,v.lon],{icon,title,zIndexOffset:300,autoPanOnFocus:false}).addTo(busesLayer).bindPopup(report,{maxWidth:300,autoPanPaddingTopLeft:[12,178],autoPanPaddingBottomRight:[12,44]});
    m._markerHtml=html;m._reportElement=report;
    m.on('popupopen',()=>{state.openVehicleId=v.id});m.on('popupclose',()=>{if(state.openVehicleId===v.id)state.openVehicleId=null;queueMicrotask(renderBuses)});state.markers.set(v.id,m);
   }else {
    // Keep the same popup, details state and action buttons while adopting the newest validated source report.
    updateBusReport(m._reportElement,v,meta);m.options.title=title;m.getElement()?.setAttribute('title',title);
    if(m._markerHtml!==html){m.setIcon(icon);m._markerHtml=html;}
    m.setLatLng([v.lat,v.lon]);
    if(m.isPopupOpen())updateOpenPopup(m);
   }
  }for(const [id,m]of state.markers)if(!visible.has(id)){if(m.isPopupOpen())m.closePopup();busesLayer.removeLayer(m);state.markers.delete(id)}
  $('nationalBusCount').textContent=!state.showBuses?'אוטובוסים מוסתרים':list.length?list.length+(state.previewFilter?' אוטובוסים במסלול':' אוטובוסים')+(!state.station&&state.areaError?' · רענון חסר':state.busy?' · רענון…':''):state.busy?'בודק דיווחים…':state.stationError||state.areaError?'הדיווחים אינם זמינים כרגע':!state.station&&(state.map.getZoom()<11||!state.areaBBox)?'חפש מקום או הגדל את המפה':'אין דיווחים עדכניים';$('nationalBusCount').classList.toggle('has-buses',list.length>0);
  $('nationalFocus').disabled=!list.length;
  clearTimeout(busExpiryTimer);if(list.length){const expires=list.map(v=>Math.min(...[v.sourceObservedAt,v.source==='open-bus-stride-siri'?v.snapshotAt:v.sourceResponseAt].map(at=>Date.parse(at)+180000)));busExpiryTimer=setTimeout(renderBuses,Math.max(1,Math.min(...expires)-Date.now()+1));}
 }
 function renderArrivals(){clearTimeout(arrivalExpiryTimer);const output=$('stationArrivals');output.replaceChildren();if(!state.station)return;const data=state.stationData,now=Date.now(),rows=(data?.arrivals||[]).filter(r=>N.fresh(data.sourceResponseAt,now)&&N.fresh(r.sourceObservedAt,now)&&N.fresh(r.sourceResponseAt,now)&&Date.parse(r.reportedArrivalAt)>=now-60000&&routeVisible(r));
  if(!rows.length){const p=document.createElement('p');p.className='station-empty';p.textContent=state.busy?'בודק זמני הגעה…':state.stationError?'לא ניתן לקבל זמני הגעה כרגע.':'אין תחזיות עדכניות כרגע.';output.append(p);return;}
  const deadlines=[];
  for(const a of rows.slice(0,14)){const row=document.createElement('button'),quality=N.arrivalUpdate(a,{now,sourceResponseAt:data.sourceResponseAt});row.type='button';row.className='station-arrival';row.dataset.updateLevel=quality.level;const dest=data.routes.find(r=>String(r.routeId)===String(a.routeId)&&String(r.operatorRef)===String(a.operatorRef))?.headsign||'יעד חסר',minutes=Math.max(1,Math.ceil((Date.parse(a.reportedArrivalAt)-now)/60000));
   row.innerHTML='<span class="line-badge">'+esc(a.line)+'</span><span class="arrival-destination">'+esc(dest)+'<small>'+esc(quality.label)+'</small></span><strong class="arrival-time">'+minutes+'<small>דק׳</small></strong>';row.title='צבע לפי טריות דיווח המקור';row.onclick=()=>selectLine(String(a.line),String(a.routeId),String(a.operatorRef));output.append(row);
   for(const clock of [a.sourceObservedAt,a.sourceResponseAt,data.sourceResponseAt])for(const age of [60000,120000,180000]){const at=Date.parse(clock)+age+1;if(at>now)deadlines.push(at);}
   deadlines.push(Date.parse(a.reportedArrivalAt)+60001);
  }
  arrivalExpiryTimer=setTimeout(renderArrivals,Math.max(1,Math.min(...deadlines)-now));
 }
 function renderLineChoices(){const output=$('stationLines');output.replaceChildren();const lines=state.station?D.linesAt(state.station.code).sort((a,b)=>a.localeCompare(b,'he',{numeric:true})):[],select=$('stationLineSelect');select.replaceChildren();for(const line of [null,...lines]){const option=document.createElement('option');option.value=line||'';option.textContent=line?'קו '+line:'כל הקווים';select.append(option)}select.value=state.line||'';const quick=[...new Set([state.line,...(state.stationData?.arrivals||[]).map(a=>String(a.line)),...lines].filter(Boolean))].slice(0,5);for(const line of quick){const b=document.createElement('button');b.type='button';b.className='line-choice';b.textContent=line||'כל הקווים';b.setAttribute('aria-pressed',String(state.line===line));b.onclick=()=>selectLine(line);output.append(b)}}
 async function selectLine(line,routeId=null,operatorRef=null){clearPreview();const revision=state.revision,token=state.lineRevision=(state.lineRevision||0)+1;state.line=line;state.routeId=routeId;state.operatorRef=operatorRef;renderLineChoices();renderArrivals();renderBuses();if(!line){root.SafeBusApp.clearSelection();$('directionWrap').hidden=true;renderStops();return;}
  $('line').value=line;$('stop').value=state.station.code;await root.SafeBusApp.applySelection();if(!state.station||state.line!==line||state.revision!==revision||state.lineRevision!==token)return;
  if(routeId){const idx=root.SafeBusApp.state.allRoutes.findIndex(r=>String(r.properties.routeId)===routeId&&(!operatorRef||String(r.properties.agencyId)===operatorRef));if(idx<0){root.SafeBusApp.clearSelection();state.routeId=routeId;$('directionWrap').hidden=true;toast('מסלול המקור חסר במאגר.');renderStops();return;}if(idx>=0){$('direction').value=String(idx);$('direction').dispatchEvent(new Event('change'))}}
  if(root.SafeBusApp.state.stopMarker)state.map.removeLayer(root.SafeBusApp.state.stopMarker);const route=root.SafeBusApp.state.route;state.routeId=route?String(route.properties.routeId):null;state.operatorRef=route?String(route.properties.agencyId):null;renderArrivals();renderBuses();renderStops();
 }
 async function selectStop(code){clearPreview();const s=state.stops.find(x=>x.code===String(code));if(!s)return;saveSearch({kind:'stop',label:s.name,code:s.code});state.searchRevision++;searchController?.abort();$('searchSubmit').disabled=false;stationController?.abort();areaController?.abort();state.areaRevision++;state.revision++;state.station=s;state.stationData=null;state.stationError=null;state.line=null;state.routeId=null;state.operatorRef=null;root.SafeBusApp.clearSelection();$('stop').value=s.code;$('placeSearch').value=s.name;$('stationTitle').textContent=s.name;$('stationCode').textContent='תחנה '+s.code;coverage('דיווחי התחנה '+s.code);$('stationDock').hidden=false;$('stationDock').classList.remove('minimized');$('stationBody').hidden=false;$('dockToggle').setAttribute('aria-expanded','true');$('directionWrap').hidden=true;hideSearch();drawSelected();renderLineChoices();state.map.setView([s.lat,s.lon],Math.max(16,state.map.getZoom()),{animate:false});await refreshStation();}
 function closeStation(){clearPreview();stationController?.abort();state.revision++;state.station=null;state.stationData=null;state.stationError=null;state.line=null;state.routeId=null;state.operatorRef=null;root.SafeBusApp.clearSelection();$('stationDock').hidden=true;drawSelected();renderBuses();refreshArea();}
 async function refreshStation(){if(!state.station)return;const revision=state.revision,code=state.station.code;stationController?.abort();stationController=new AbortController();state.busy=true;renderArrivals();renderBuses();$('stationRefresh').disabled=true;
  try{const raw=await json('./api/national?kind=station&stopCode='+encodeURIComponent(code),stationController.signal);if(revision!==state.revision)return;state.stationData=N.station(raw,code);state.stationError=null;renderLineChoices();$('stationUpdated').textContent=N.fresh(raw.sourceResponseAt,Date.now())?'מקור '+new Date(raw.sourceResponseAt).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit'}):'מקור ישן';$('stationCoverage').textContent=raw.partial?'כיסוי חלקי':D.linesAt(code).length+' קווים';$('stationCoverage').hidden=!raw.partial;}
  catch(e){if(e.name==='AbortError'||revision!==state.revision)return;state.stationError=e.message;state.stationData=null;$('stationUpdated').textContent='לא זמין';$('stationCoverage').hidden=true;}
  finally{if(revision===state.revision){state.busy=false;$('stationRefresh').disabled=false;renderArrivals();renderBuses()}}
 }
 function currentBBox(){const b=state.map.getBounds();return [Math.max(34,b.getWest()),Math.max(29,b.getSouth()),Math.min(36,b.getEast()),Math.min(34,b.getNorth())].map(n=>Number(n.toFixed(5)))}
 async function refreshArea(){if(state.station||!state.showBuses)return;let bbox=currentBBox(),following=false;const tooWide=bbox[2]-bbox[0]>.4||bbox[3]-bbox[1]>.4;if(tooWide&&(state.openVehicleId||state.previewFilter)){const rows=N.vehicles(state.areaData?.vehicles||[]),v=rows.find(v=>v.id===state.openVehicleId)||rows.find(routeVisible);if(v){bbox=[Math.max(34,v.lon-.06),Math.max(29,v.lat-.06),Math.min(36,v.lon+.06),Math.min(34,v.lat+.06)].map(n=>Number(n.toFixed(5)));following=true;}else if(state.areaBBox){bbox=state.areaBBox;following=true;}}if(bbox[2]-bbox[0]>.4||bbox[3]-bbox[1]>.4||bbox[0]>=bbox[2]||bbox[1]>=bbox[3]){areaController?.abort();state.areaRevision++;state.areaData=null;state.busy=false;state.areaError=null;coverage('חפש מקום או הגדל את המפה');renderBuses();return;}
  const revision=++state.areaRevision;areaController?.abort();areaController=new AbortController();state.busy=true;state.areaError=null;renderBuses();coverage('בודק דיווחי אזור');
  try{const raw=await json('./api/national?kind=area&bbox='+bbox.join(','),areaController.signal);if(revision!==state.areaRevision||state.station)return;const metadataTask=D.routeIndexFor(raw.vehicles).then(metadata=>{if(metadata?.catalogVersion!==D.version())return;state.index=metadata.routes;if(state.indexVersion!==metadata.catalogVersion){state.indexVersion=metadata.catalogVersion;state.stops=catalogStops();renderStops();}renderBuses();}).catch(()=>{});let metadataWait;await Promise.race([metadataTask,new Promise(resolve=>{metadataWait=setTimeout(resolve,1200)})]);clearTimeout(metadataWait);if(revision!==state.areaRevision||state.station)return;state.areaData=N.mergeArea(state.areaData,raw,bbox,{followedId:state.openVehicleId});state.areaBBox=bbox;coverage(following?'סביב האוטובוס':raw.coverage==='nearby-stop-reports'?'כיסוי חלקי · '+(raw.sampledStopCodes?.length||0)+' תחנות':raw.truncated?'כיסוי חלקי':'דיווחי אזור',following||raw.coverage==='nearby-stop-reports'||!!raw.truncated);}
  catch(e){if(e.name==='AbortError'||revision!==state.areaRevision)return;state.areaError=e.message;coverage('המקור אינו זמין');}
  finally{if(revision===state.areaRevision&&!state.station){state.busy=false;renderBuses()}}
 }
 function hideSearch(){clearTimeout(searchTimer);$('searchResults').hidden=true;$('placeSearch').setAttribute('aria-expanded','false')}
 function showResults(local,places=[],note=''){const list=$('searchResults');list.replaceChildren();state.searchResults=[];const add=(item,label,detail,action)=>{const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.innerHTML='<span>'+esc(label)+'</span><small>'+esc(detail)+'</small>';b.onclick=action;li.append(b);list.append(li);state.searchResults.push(b)};
  for(const p of places)add(p,p.name,'מקום · OpenStreetMap',()=>choosePlace(p));for(const s of local)add(s,s.name,'תחנה '+s.code,()=>selectStop(s.code));
  if(note){const li=document.createElement('li');li.className='search-note';li.textContent=note;list.append(li)}list.hidden=!list.children.length;$('placeSearch').setAttribute('aria-expanded',String(!list.hidden));
 }
 function localSearch(){const text=$('placeSearch').value.trim();const c=state.map.getCenter();return N.stopSearch(state.stops,text,{lat:c.lat,lon:c.lng})}
 async function search(event){clearTimeout(searchTimer);event?.preventDefault();const q=$('placeSearch').value.trim();if(q.length<2){toast('הקלד כתובת, מקום, שם תחנה או מספר תחנה');return;}
  saveSearch({kind:'query',label:q});const local=localSearch();if(/^\d{3,7}$/.test(q)&&local.some(s=>s.code===q)){selectStop(q);return;}
  const revision=++state.searchRevision;searchController?.abort();searchController=new AbortController();$('searchSubmit').disabled=true;showResults(local,[],'מחפש כתובות ומקומות…');
  try{const raw=await json('./api/search?q='+encodeURIComponent(q),searchController.signal);if(revision!==state.searchRevision)return;showResults(local,raw.places||[],raw.places?.length?'':'לא נמצא מקום. נסה רחוב ועיר.');}
  catch(e){if(e.name==='AbortError'||revision!==state.searchRevision)return;showResults(local,[],'חיפוש כתובות לא זמין. אפשר לבחור תחנה.');}
  finally{if(revision===state.searchRevision)$('searchSubmit').disabled=false}
 }

 function clearPreview(){const active=!!state.previewFilter;state.previewRevision++;state.previewRoutes=[];state.previewFilter=null;previewLayer?.clearLayers();if($('routePreview'))$('routePreview').hidden=true;if(active){const layer=root.SafeBusApp.state.routeLayer;if(layer&&!state.map.hasLayer(layer))layer.addTo(state.map);$('stationDock').hidden=!state.station;renderStops();renderArrivals();renderBuses();}}
 async function previewRoute(line,routeId,operatorRef){
  clearPreview();const revision=state.previewRevision;
  try{
   const routes=await D.routesFor(line),match=routes.filter(f=>String(f.properties.routeId)===String(routeId)&&String(f.properties.agencyId)===String(operatorRef));
   if(revision!==state.previewRevision)return;
   if(!match.length){toast('אין תוואי GTFS שמתאים למפעיל ולמסלול המדווחים.');return;}
   state.previewRoutes=match;state.previewFilter={line:String(line),routeId:String(routeId),operatorRef:String(operatorRef)};const previousLayer=root.SafeBusApp.state.routeLayer;if(previousLayer)state.map.removeLayer(previousLayer);$('stationDock').hidden=true;renderArrivals();renderBuses();renderStops();const f=match[0],collection={type:'FeatureCollection',features:match};L.geoJSON(collection,{style:feature=>({color:'#1765d7',weight:6,opacity:.85,dashArray:match.length>1||feature.properties.suspect?'8 7':null})}).addTo(previewLayer);
   $('routePreviewTitle').textContent=match.length===1?'קו '+line+' · '+f.properties.origin+' ← '+f.properties.destination:'קו '+line+' · '+match.length+' חלופות מסלול';
   $('routePreviewNote').textContent='מסלול מתוכנן'+(match.length>1?' · חלופות':'')+(f.properties.suspect?' · תוואי חריג':'');$('routePreviewNote').title='כיוון נסיעת הרכב לא אומת'+(match.length>1?' ואין שיוך לחלופה מסוימת':'');
   $('routePreview').hidden=false;
   state.map.closePopup();state.map.fitBounds(L.geoJSON(collection).getBounds(),{padding:[35,170],maxZoom:16,animate:false});
  }catch{if(revision===state.previewRevision)toast('לא ניתן לטעון כרגע את מסלול המקור.');}
 }
 function stopTraffic(message=''){
  state.trafficRevision++;state.trafficEnabled=false;clearInterval(trafficTimer);clearTimeout(trafficAgeTimer);
  if(state.traffic)state.map.removeLayer(state.traffic);state.traffic=null;
  $('trafficLayerToggle').setAttribute('aria-pressed','false');$('trafficLegend').hidden=true;state.trafficClock=null;state.trafficStatus=message?message:'off';
  if(message)toast(message);
 }
 async function toggleTraffic({automatic=false}={}){
  if(state.trafficEnabled){if(automatic)return;state.trafficWanted=false;try{localStorage.setItem('eifo-traffic-preference','off')}catch{}stopTraffic();return;}
  state.trafficWanted=true;if(!automatic)try{localStorage.setItem('eifo-traffic-preference','on')}catch{}
  const button=$('trafficLayerToggle'),note=$('trafficLayerNote'),revision=++state.trafficRevision;button.disabled=true;note.hidden=true;
  try{
   const config=await json('./api/traffic?kind=status');if(revision!==state.trafficRevision)return;state.trafficStatus=config.state||'configured';
   if(!config.available){const noCoverage=config.state==='coverage-unavailable';button.title=noCoverage?'TomTom מחובר · אין כיסוי בישראל':'טרם חובר לשרת DEV';if(noCoverage){note.textContent='אין כיסוי';note.hidden=false;}if(!automatic)toast(noCoverage?'אין כיסוי בישראל':'פקקים טרם חוברו לשרת DEV.');return;}
   if(config.state==='quota-exhausted'){button.title='מכסת TomTom נוצלה';if(!automatic)toast('מכסת TomTom נוצלה.');return;}button.title='הצג או הסתר פקקים';
   state.trafficEnabled=true;state.trafficStatus='loading';button.setAttribute('aria-pressed','true');
   const expire=code=>{if(revision!==state.trafficRevision)return;const empty=code==='TRAFFIC_NO_DATA';stopTraffic(empty?(automatic?'':'אין נתונים'):code==='TRAFFIC_QUOTA_EXHAUSTED'?'מכסת TomTom נוצלה.':code==='TRAFFIC_EXPIRED'?'תוקף הפקקים פג.':'פקקים אינם זמינים כרגע.');state.trafficStatus=empty?'no-data':code==='TRAFFIC_QUOTA_EXHAUSTED'?'quota-exhausted':code==='TRAFFIC_EXPIRED'?'expired':'unavailable';if(empty){note.textContent='אין נתונים';note.hidden=false;}};
   state.traffic=root.SafeBusTrafficTiles.create({onFailure:expire,onClock:clock=>{
    if(revision!==state.trafficRevision)return;if(clock.hasData!==true){state.trafficStatus='no-data';state.trafficClock=null;$('trafficLegend').hidden=true;return;}state.trafficStatus='active';note.hidden=true;state.trafficClock=clock;clearTimeout(trafficAgeTimer);$('trafficLegend').hidden=false;
    $('trafficClock').textContent='תגובת ספק '+new Date(clock.originatedAt).toLocaleTimeString('he-IL',{hour:'2-digit',minute:'2-digit',second:'2-digit'});$('trafficClock').title='זמן תגובת הספק; זמן מדידת הכביש אינו מסופק';
   }});
   state.traffic.addTo(state.map);trafficAgeTimer=setTimeout(()=>expire(state.trafficStatus==='no-data'?'TRAFFIC_NO_DATA':'TRAFFIC_UNAVAILABLE'),12000);
   trafficTimer=setInterval(()=>{if(revision===state.trafficRevision&&state.traffic&&!document.hidden){$('trafficLegend').hidden=true;state.traffic.redraw();trafficAgeTimer=setTimeout(()=>expire(state.trafficStatus==='no-data'?'TRAFFIC_NO_DATA':'TRAFFIC_UNAVAILABLE'),12000);}},60000);
  }catch{stopTraffic(automatic?'':'פקקים אינם זמינים כרגע.');state.trafficStatus='unavailable';}finally{button.disabled=false}
 }
 function init(){if(state.ready||!root.SafeBusApp?.state.map)return;state.ready=true;state.map=root.SafeBusApp.state.map;$('map').addEventListener('click',e=>{const b=e.target.closest?.('[data-stop-choice]');if(b)selectStop(b.dataset.stopChoice);const route=e.target.closest?.('[data-bus-route]');if(route)previewRoute(route.dataset.busLine,route.dataset.busRoute,route.dataset.busOperator)});state.map.removeLayer(root.SafeBusApp.state.vehicleLayer);state.map.createPane('trafficPane');state.map.getPane('trafficPane').style.zIndex=350;state.map.getPane('trafficPane').style.pointerEvents='none';stopsLayer=L.layerGroup().addTo(state.map);busesLayer=L.layerGroup().addTo(state.map);selectedLayer=L.layerGroup().addTo(state.map);previewLayer=L.layerGroup().addTo(state.map);$('closeRoutePreview').onclick=clearPreview;$('countryView').onclick=()=>{closeStation();state.map.fitBounds(L.latLngBounds(state.stops.map(s=>[s.lat,s.lon])),{padding:[20,110],animate:false});};
  state.stops=catalogStops();try{state.searchHistory=N.searchHistory(JSON.parse(localStorage.getItem('eifo-search-history')||'[]'))}catch{}
  try{const p=JSON.parse(localStorage.getItem('eifo-national-map')||'null');if(p&&C.validCoord(p.lat,p.lon)&&p.zoom>=7&&p.zoom<=19)state.map.setView([p.lat,p.lon],p.zoom,{animate:false})}catch{}

  $('searchForm').onsubmit=search;$('placeSearch').onfocus=showHistory;$('placeSearch').oninput=()=>{state.searchRevision++;searchController?.abort();$('searchSubmit').disabled=false;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(!$('placeSearch').value.trim())showHistory();else showResults(localSearch(),[],$('placeSearch').value.trim().length>=2?'לחיפוש כתובת, לחץ חיפוש או Enter':'')},160)};
  $('placeSearch').onkeydown=e=>{if(e.key==='Escape')hideSearch();if(e.key==='ArrowDown'&&state.searchResults.length){e.preventDefault();state.searchResults[0].focus()}};$('searchResults').onkeydown=e=>{const i=state.searchResults.indexOf(document.activeElement);if(e.key==='Escape'){hideSearch();$('placeSearch').focus()}if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();state.searchResults[(i+(e.key==='ArrowDown'?1:-1)+state.searchResults.length)%state.searchResults.length]?.focus()}};
  $('stationLineSelect').onchange=()=>selectLine($('stationLineSelect').value||null);$('closeStation').onclick=closeStation;$('stationRefresh').onclick=refreshStation;$('dockToggle').onclick=()=>{const hide=!$('stationBody').hidden;$('stationBody').hidden=hide;$('stationDock').classList.toggle('minimized',hide);$('dockToggle').setAttribute('aria-expanded',String(!hide))};
  $('stationsToggle').onclick=()=>{state.showStops=!state.showStops;$('stationsToggle').setAttribute('aria-pressed',String(state.showStops));renderStops()};$('busesToggle').onclick=()=>{state.showBuses=!state.showBuses;$('busesToggle').setAttribute('aria-pressed',String(state.showBuses));renderBuses();if(state.showBuses&&!state.station)refreshArea()};$('trafficLayerToggle').onclick=toggleTraffic;
  $('nationalFocus').onclick=()=>{const list=visibleVehicles();if(list.length){const bounds=L.latLngBounds(list.map(v=>[v.lat,v.lon]));if(state.station)bounds.extend([state.station.lat,state.station.lon]);state.map.fitBounds(bounds.pad(.15),{maxZoom:17,animate:false})}};
  $('myLocation').onclick=()=>{if(!navigator.geolocation){toast('הדפדפן אינו תומך בקבלת מיקום');return;}navigator.geolocation.getCurrentPosition(p=>{if(!C.validCoord(p.coords.latitude,p.coords.longitude)){toast('המיקום מחוץ לתחום המפה הארצית');return;}closeStation();state.map.setView([p.coords.latitude,p.coords.longitude],16,{animate:false})},()=>toast('לא התקבל מיקום. אפשר לחפש כתובת או להזיז את המפה.'),{enableHighAccuracy:false,timeout:10000,maximumAge:60000})};
  $('map').addEventListener('toggle',e=>{if(!e.target.matches?.('.bus-source'))return;for(const m of state.markers.values()){const popup=m.getPopup();if(m.isPopupOpen()&&popup.getElement()?.contains(e.target)){updateOpenPopup(m);break;}}},true);
  state.map.on('autopanstart',()=>{state.popupPanning=true;clearTimeout(areaTimer)});state.map.on('movestart',()=>{if(!state.station&&!state.popupPanning){areaController?.abort();state.areaRevision++;state.busy=false;renderBuses()}});state.map.on('moveend',()=>{renderStops();saveMap();if(state.popupPanning){state.popupPanning=false;return;}clearTimeout(areaTimer);areaTimer=setTimeout(refreshArea,550)});state.map.on('click',hideSearch);
  $('direction').addEventListener('change',()=>{if(!state.station||!state.line)return;state.routeId=String(root.SafeBusApp.state.allRoutes[Number($('direction').value)]?.properties.routeId||'');state.operatorRef=String(root.SafeBusApp.state.allRoutes[Number($('direction').value)]?.properties.agencyId||'');if(root.SafeBusApp.state.stopMarker)state.map.removeLayer(root.SafeBusApp.state.stopMarker);renderArrivals();renderBuses();renderStops()});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(state.trafficEnabled){stopTraffic();toggleTraffic();}state.station?refreshStation():refreshArea()}});setInterval(()=>{if(!document.hidden&&!state.busy)state.station?refreshStation():refreshArea()},20000);setInterval(()=>{if(state.ready){renderArrivals();renderBuses()}},15000);renderStops();refreshArea();const params=new URL(location.href).searchParams,a=Number(params.get('lat')),b=Number(params.get('lon'));if(params.has('lat')&&params.has('lon')&&C.validCoord(a,b))state.map.setView([a,b],15,{animate:false});try{state.trafficWanted=localStorage.getItem('eifo-traffic-preference')!=='off'}catch{}if(params.get('traffic')==='1')state.trafficWanted=true;if(state.trafficWanted)toggleTraffic({automatic:true});$('catalogStatus').textContent=state.stops.length.toLocaleString('he-IL')+' תחנות · '+D.allLines().length+' קווים';$('importStatus').textContent='GTFS '+D.version();$('trafficApply').onclick=()=>{root.SafeBusApp.setPanel(false);toggleTraffic()};
 }
 async function services(){const status=$('trafficConnectionStatus');if(!status)return;status.textContent='בודק חיבור…';try{const config=await json('./api/traffic?kind=status');if(!state.trafficEnabled)state.trafficStatus=config.state;status.textContent=config.state==='coverage-unavailable'?'TomTom מחובר · אין כיסוי בישראל':state.trafficStatus==='no-data'?'מחובר · אין נתונים באזור':!config.available?'טרם חובר לשרת DEV':config.state==='quota-exhausted'?'המכסה נוצלה':state.trafficStatus==='active'?'פעיל במפה':state.trafficEnabled?'מחובר · בודק נתונים':'מחובר · שכבה כבויה';}catch{status.textContent='הבדיקה לא זמינה';}}
 function diagnosticText(){
  const app=root.SafeBusApp.state,data=state.station?state.stationData:state.areaData,rows=state.showBuses?visibleVehicles():[],error=state.station?state.stationError:state.areaError;
  const routes=state.previewRoutes.length?state.previewRoutes:app.route?[app.route]:[],points=routes.reduce((n,r)=>n+(r.geometry?.coordinates?.length||0),0),stamp=at=>at||'חסר';
  const traffic=!state.trafficEnabled&&state.trafficStatus==='unknown'?'טרם נבדק':state.trafficStatus==='coverage-unavailable'?'TomTom מחובר · אין כיסוי בישראל':state.trafficStatus==='no-data'?'אין נתונים באזור':state.trafficStatus==='expired'?'מידע פג':state.trafficStatus==='not-connected'?'טרם חובר לשרת DEV':state.trafficStatus==='active'?'פעיל · TomTom':state.trafficStatus==='configured'||state.trafficStatus==='off'?'כבוי':state.trafficStatus==='quota-exhausted'?'המכסה נוצלה':state.trafficStatus==='loading'?'טוען':state.trafficStatus==='unavailable'?'לא זמין':state.trafficStatus;
  return ['איפה בטוח? DEV-9.3.7 — מצב המערכת',state.station?'תחנה '+state.station.code+(state.line?' · קו '+state.line:' · כל הקווים'):'אזור המפה · ללא תחנה נבחרת','מפה: '+(app.tileSource||'טרם נטענה'),'GTFS: '+D.version()+' · '+(routes.length?routes.length+' תוואים · '+points+' נקודות':'ללא תוואי נבחר'),'אוטובוסים: '+rows.length+(state.showBuses?' דיווחים עדכניים':' · שכבה מוסתרת'),'תחזיות: '+(state.station?$('stationArrivals').querySelectorAll('.station-arrival').length+' עדכניות':'לפי תחנה'),'מקור: '+(error?'כשל · '+error:data?'תגובה התקבלה':state.busy?'בודק':'טרם נבדק'),'תגובת מקור: '+stamp(data?.sourceResponseAt),'זמן דיווח ראשון: '+stamp(rows[0]?.sourceObservedAt),'צילום ארכיון: '+stamp(rows[0]?.snapshotAt),'פקקים: '+traffic,...(state.trafficClock?['תגובת TomTom: '+state.trafficClock.originatedAt]:[]),'שרת: DEV · LIVE-WORK מקור נפרד','כתובת: '+location.origin+location.pathname].join('\n');
 }
 async function diagnose(){
  const out=$('diagnostic');out.textContent=diagnosticText()+'\n\nבודק חיבור…';$('diagnose').disabled=true;
  try{
   const probes=await Promise.all([['LIVE-WORK דרך DEV','./api/live?kind=health'],['TomTom','./api/traffic?kind=status']].map(async([name,url])=>{try{const r=await json(url);if(name==='TomTom'){if(!state.trafficEnabled)state.trafficStatus=r.state;return name+': '+(r.state==='coverage-unavailable'?'מחובר · אין כיסוי בישראל':r.available?'מחובר':'טרם חובר לשרת DEV')}return name+': נגיש'}catch{return name+': לא זמין'}}));
   if(state.station)await refreshStation();else await refreshArea();
   out.textContent=diagnosticText()+'\n\nבדיקות חיבור:\n'+probes.join('\n');
  }finally{$('diagnose').disabled=false;}
 }
 function loadError(){ $('nationalBusCount').textContent='מאגר התחנות לא זמין';$('importStatus').textContent='הטעינה נכשלה';toast('לא ניתן לטעון תחנות. נסה לרענן.'); }

 root.SafeBusNational={state,init,selectStop,selectLine,closeStation,refreshArea,refreshStation,renderStops,renderBuses,search,toggleTraffic,services,previewRoute,stopTraffic,diagnosticText,diagnose,loadError};
})(window);
