'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),http=require('node:http'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const root=path.resolve(__dirname,'..'),folder=path.join(root,'dist'),handlers={};for(const name of ['live','national','dataset','search','traffic'])handlers[name]=(await import(pathToFileURL(path.join(root,'api/'+name+'.mjs')).href)).GET;const security=JSON.parse(await fs.readFile(path.join(root,'vercel.json'),'utf8')).headers[0].headers;
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname.startsWith('/api/')){const handler=handlers[url.pathname.slice(5)];if(!handler){res.writeHead(404);res.end();return;}const r=await handler(new Request(url));res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));return;}const file=path.resolve(folder,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(folder+path.sep)){res.writeHead(403);res.end();return;}const data=await fs.readFile(file),type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,...Object.fromEntries(security.map(h=>[h.key,h.value]))});res.end(data)}catch{res.writeHead(404);res.end('Unavailable')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
let debugPage;try{const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],searchCalls=[];debugPage=page;page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('BROWSER CONSOLE ERROR',m.text())});page.on('request',r=>{if(r.url().includes('/api/search?'))searchCalls.push(r.url())});const publicBase=process.env.DEV_BASE_URL;if(publicBase&&publicBase!=='https://eifo-batuach-dev.vercel.app')throw Error('Public QA is restricted to the canonical DEV site');const base=publicBase||'http://127.0.0.1:'+server.address().port;const response=await page.goto(base,{waitUntil:'domcontentloaded'});assert.match(response.headers()['content-security-policy'],/script-src 'self'/);await page.waitForFunction(()=>SafeBusNational.state.ready,null,{timeout:40000});assert.ok(await page.evaluate(()=>SafeBusNational.state.stops.length>20000));assert.equal(await page.evaluate(()=>SafeBusApp.state.route),null,'Countrywide opening must not silently select Gila');assert.equal(await page.locator('.national-stop-pin').count(),0,'Country overview must leave the map clear of station clusters');
const size=await page.locator('#map').evaluate(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}));assert.deepEqual(size,{width:1440,height:900});await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'country.png'});
for(const query of ['רוטשילד תל אביב','מרכז חורב חיפה','אילת']){const before=searchCalls.length;await page.locator('#placeSearch').fill(query);await page.waitForTimeout(250);assert.equal(searchCalls.length,before,'Typing searches the local catalog; geocoder is explicit-submit only');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>!document.getElementById('searchSubmit').disabled,{timeout:30000});const places=page.locator('#searchResults li button').filter({hasText:'OpenStreetMap'});assert.ok(await places.count(),'Real address search must return places for '+query);await places.first().click();const p=await page.evaluate(()=>SafeBusNational.state.map.getCenter());assert.ok(p.lat>=29&&p.lat<=34&&p.lng>=34&&p.lng<=36);console.log('REAL NATIONAL ADDRESS',query,JSON.stringify(p));await page.waitForTimeout(1200)}
await page.locator('#placeSearch').fill('');await page.waitForTimeout(220);assert.ok(await page.locator('.recent-search').count()>0,'Search history is available without another screen');await page.locator('.recent-search').first().click();await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>SafeBusNational.state.ready,null,{timeout:40000});await page.locator('#placeSearch').fill('');await page.locator('#placeSearch').click();await page.waitForTimeout(220);assert.ok(await page.locator('.recent-search').count()>0,'Search history survives reload on this device');console.log('REAL SEARCH HISTORY saved and reopened');
await page.locator('#placeSearch').fill('23014');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='23014'&&!SafeBusNational.state.busy,{timeout:40000});assert.equal(await page.evaluate(()=>SafeBusNational.state.stationError),null);assert.ok(await page.locator('#stationLineSelect option').count()>20);assert.ok((await page.locator('.stop-cluster').allTextContents()).every(x=>!x.trim()),'Grouped stations use quiet dots instead of map-covering numeric circles');console.log('REAL NATIONAL STATION',JSON.stringify(await page.evaluate(()=>({code:SafeBusNational.state.station.code,arrivals:SafeBusNational.state.stationData.arrivals.length,vehicles:SafeBusNational.state.stationData.vehicles.length,partial:SafeBusNational.state.stationData.partial}))));
await page.locator('#placeSearch').fill('3441');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='3441'&&!SafeBusNational.state.busy,{timeout:40000});await page.locator('#stationLineSelect').selectOption('10א');await page.waitForFunction(()=>SafeBusApp.state.route?.properties.line==='10א'&&SafeBusNational.state.routeId,{timeout:35000});assert.ok(await page.locator('.leaflet-overlay-pane path').count()>0,'Hebrew line suffix loads its real national GTFS route');console.log('REAL HEBREW-SUFFIX ROUTE',JSON.stringify(await page.evaluate(()=>({line:SafeBusApp.state.route.properties.line,points:SafeBusApp.state.route.geometry.coordinates.length}))));await page.locator('#placeSearch').fill('23014');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='23014'&&!SafeBusNational.state.busy,{timeout:40000});
if(publicBase){
 const deployed=await (await page.request.get(base+'/deployment.json')).json();assert.equal(deployed.version,'DEV-9.3.7');assert.equal(deployed.branch,'dev/vehicle-history-map-20261009');
 assert.equal(await page.locator('html').getAttribute('dir'),'rtl');console.log('PUBLIC REAL DEPLOYMENT',JSON.stringify(deployed));
 await page.locator('#closeStation').click();
 let realBuses=0;
 async function clickExposedBus(){const index=await page.locator('.bus-pin').evaluateAll(nodes=>{const options=nodes.map((e,i)=>{const r=e.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2;return {i,x,y,exposed:x>0&&y>0&&x<innerWidth&&y<innerHeight&&document.elementFromPoint(x,y)?.closest('.bus-pin')===e}}).filter(p=>p.exposed);options.sort((a,b)=>Math.hypot(a.x-innerWidth/2,a.y-innerHeight/2)-Math.hypot(b.x-innerWidth/2,b.y-innerHeight/2));return options[0]?.i??-1});assert.ok(index>=0,'A real bus marker must be visible and clickable without crossing map controls');await page.locator('.bus-pin').nth(index).click({timeout:5000});}

 for(const query of ['מרכז חורב חיפה','נצרת']){
  await page.locator('#placeSearch').fill(query);await page.locator('#searchSubmit').click();await page.waitForFunction(()=>!document.getElementById('searchSubmit').disabled&&!document.getElementById('searchResults').textContent.includes('מחפש כתובות'),{timeout:30000});
  const places=page.locator('#searchResults li button').filter({hasText:'OpenStreetMap'});if(!await places.count()){console.log('PUBLIC REAL AREA NOT FOUND',query);continue;}await places.first().click();
  await page.waitForTimeout(1300);await page.waitForFunction(()=>!SafeBusNational.state.busy,{timeout:45000});
  const report=await page.evaluate(()=>({error:SafeBusNational.state.areaError,rawCount:SafeBusNational.state.areaData?.vehicles?.length||0,shown:SafeBusNational.state.markers.size,source:SafeBusNational.state.areaData?.coverage,vehicles:(SafeBusNational.state.areaData?.vehicles||[]).slice(0,3)}));
  if(query==='נצרת'){assert.ok(report.shown>0,'Positive Nazareth route-number proof requires actual fresh source reports');const labels=await page.locator('.bus-marker-label').evaluateAll(nodes=>nodes.map(n=>n.firstChild.textContent.trim()));assert.ok(labels.every(x=>x&&x!=='?'),'Nazareth source reports must resolve to validated public line numbers');console.log('PUBLIC REAL NAZARETH LINE LABELS',JSON.stringify(labels));}realBuses+=report.shown;console.log('PUBLIC REAL AREA',query,JSON.stringify(report));
  if(report.shown){
   await clickExposedBus();await page.locator('.bus-report').waitFor({state:'visible'});await page.locator('.bus-source summary').click();await page.evaluate(()=>SafeBusNational.renderBuses());assert.equal(await page.locator('.bus-source').evaluate(e=>e.open),true,'Refreshing ages must preserve expanded report details');assert.match(await page.locator('.bus-report').innerText(),/זמן דיווח/);
   await page.waitForTimeout(450);assert.ok(await page.locator('.leaflet-popup').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=170&&r.bottom<=innerHeight-25}),'Expanded source details must stay within the usable screen');await page.screenshot({path:'dev-public-real-bus.png'});
   if(query==='נצרת'){
    const before=await page.evaluate(()=>{const s=SafeBusNational.state,m=s.markers.get(s.openVehicleId),v=s.areaData.vehicles.find(v=>v.id===s.openVehicleId);window.realFollow={id:s.openVehicleId,popup:m.getPopup(),report:m._reportElement};return {id:s.openVehicleId,at:v.sourceObservedAt,lat:v.lat,lon:v.lon}});
    await page.waitForTimeout(21000);await page.evaluate(()=>SafeBusNational.refreshArea());
    const after=await page.evaluate(()=>{const s=SafeBusNational.state,m=s.markers.get(realFollow.id),v=s.areaData.vehicles.find(v=>v.id===realFollow.id);return {id:realFollow.id,at:v?.sourceObservedAt,lat:v?.lat,lon:v?.lon,open:!!m?.isPopupOpen(),samePopup:m?.getPopup()===realFollow.popup,sameReport:m?._reportElement===realFollow.report,attached:!!m&&m.getPopup().getLatLng().equals(m.getLatLng()),expanded:m?._reportElement.querySelector('.bus-source').open}});
    assert.ok(after.open&&after.samePopup&&after.sameReport&&after.attached&&after.expanded,'Actual source refresh preserves the selected bus bubble');console.log('PUBLIC REAL OPEN BUS SOURCE REFRESH',JSON.stringify({before,after,positionChanged:before.lat!==after.lat||before.lon!==after.lon,clockChanged:before.at!==after.at}));await page.screenshot({path:'dev-public-real-bus-follow-refresh.png'});
   }
   const route=page.locator('.bus-report [data-bus-route]');if(await route.isVisible()){await route.click();await page.locator('#routePreview').waitFor({state:'visible'});assert.ok(await page.locator('.leaflet-overlay-pane path').count()>0);const focus=await page.evaluate(()=>{const s=SafeBusNational.state,f=s.previewFilter;return {filter:f,shown:s.markers.size,allMatch:[...s.markers.keys()].every(id=>s.areaData.vehicles.some(v=>v.id===id&&String(v.operatorRef)===f.operatorRef&&String(v.routeId)===f.routeId))}});assert.equal(focus.allMatch,true);console.log('PUBLIC REAL BUS ROUTE FOCUS',JSON.stringify(focus));await page.screenshot({path:'dev-public-real-route-focus.png'});await page.locator('#closeRoutePreview').click();}
   await page.evaluate(()=>SafeBusNational.state.map.closePopup());
   await page.setViewportSize({width:390,height:844});await page.waitForTimeout(900);await page.waitForFunction(()=>!SafeBusNational.state.busy,{timeout:45000});const phoneReports=await page.evaluate(()=>SafeBusNational.state.markers.size);console.log('PUBLIC REAL PHONE BUS REPORTS',query,phoneReports);if(phoneReports){await clickExposedBus();await page.locator('.bus-report').waitFor({state:'visible'});await page.waitForTimeout(450);assert.equal(await page.locator('.bus-report').isVisible(),true,'Focusing an edge marker must preserve its popup');if(await page.locator('.bus-source').getAttribute('open')!==null)await page.locator('.bus-source summary').click();await page.screenshot({path:'dev-public-phone-real-bus-compact.png'});await page.locator('.bus-source summary').click();await page.waitForTimeout(450);assert.ok(await page.locator('.leaflet-popup').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=170&&r.bottom<=innerHeight-25}),'Phone source details must remain on screen');await page.screenshot({path:'dev-public-phone-real-bus.png'});await page.evaluate(()=>SafeBusNational.state.map.closePopup());}else await page.screenshot({path:'dev-public-phone-real-area.png'});await page.locator('#placeSearch').fill('');await page.waitForTimeout(220);assert.ok(await page.locator('.recent-search').count()>0,'Phone recent searches are available directly in the search field');assert.ok(await page.locator('#searchResults').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}),'Phone history stays in its viewport');await page.screenshot({path:'dev-public-phone-search-history.png'});await page.locator('.recent-search').first().click();console.log('PUBLIC REAL PHONE SEARCH HISTORY reopen passed',query);await page.setViewportSize({width:1440,height:900});await page.waitForTimeout(900);
  }
 }

 // Mixed test: simulated old deployed index, actual current GTFS files and actual source reports.
 const mismatch=await browser.newPage({viewport:{width:390,height:844}});const currentHint=await (await page.request.get(base+'/data/routes-index.json')).json();let currentLineRequests=0;
 mismatch.on('request',r=>{if(r.url().includes('/api/dataset?file=line'))currentLineRequests++});
 await mismatch.route('**/data/routes-index.json',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({...currentHint,catalogVersion:'1111111111111111'})}));
 await mismatch.goto(base+'/?lat=32.7&lon=35.3',{waitUntil:'domcontentloaded'});await mismatch.waitForFunction(()=>SafeBusNational.state.ready&&SafeBusNational.state.areaData&&!SafeBusNational.state.busy&&SafeBusNational.state.markers.size>0&&Array.from(document.querySelectorAll('.bus-marker-label')).every(n=>n.firstChild.textContent.trim()!=='?'),null,{timeout:45000});
 const recovered=await mismatch.locator('.bus-marker-label').evaluateAll(nodes=>nodes.map(n=>n.firstChild.textContent.trim()));assert.ok(recovered.length>0&&recovered.every(x=>x&&x!=='?'),'An outdated index must recover numbers from current official route files');assert.ok(currentLineRequests>0,'Recovery independently fetched current per-line metadata');console.log('MIXED GTFS VERSION REGRESSION: simulated old index / actual source vehicles',JSON.stringify({labels:recovered,lineRequests:currentLineRequests}));await mismatch.screenshot({path:'dev-public-phone-gtfs-mismatch-mixed.png'});await mismatch.close();
 console.log('PUBLIC REAL BUS MARKERS OBSERVED',realBuses,'Zero means actual marker flow was not witnessed; synthetic tests below do not substitute for it.');
 const realTraffic=await (await page.request.get(base+'/api/traffic?kind=status')).json();console.log('PUBLIC REAL TRAFFIC STATUS',JSON.stringify(realTraffic));
 if(!realTraffic.available){await page.locator('#trafficLayerToggle').click();await page.waitForFunction(()=>!document.getElementById('trafficLayerToggle').disabled);assert.equal(await page.locator('#trafficLegend').isVisible(),false);assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);if(realTraffic.state==='coverage-unavailable'){assert.equal(realTraffic.connected,true);assert.equal(realTraffic.provider,'TomTom');assert.match(await page.locator('#trafficLayerNote').innerText(),/אין כיסוי/);assert.match(await page.locator('#notice').innerText(),/כיסוי/);console.log('PUBLIC REAL TOMTOM COVERAGE BLOCKED: account connected, no active or invented traffic pixels');await page.screenshot({path:'dev-public-coverage-unavailable.png'});await page.setViewportSize({width:390,height:844});await page.locator('#trafficLayerNote').waitFor({state:'visible'});await page.screenshot({path:'dev-public-phone-coverage-unavailable.png'});await page.setViewportSize({width:1440,height:900});}else assert.match(await page.locator('#notice').innerText(),/טרם חוברו/);}
 else {
  assert.equal(realTraffic.provider,'TomTom');
  assert.equal(await page.evaluate(()=>SafeBusNational.state.trafficWanted),true,'Real traffic is wanted by default before any manual toggle');
  assert.equal(await page.evaluate(()=>SafeBusNational.state.trafficEnabled),true,'Real traffic stays active through search, source popup and route flow');
  await page.locator('#trafficLegend').waitFor({state:'visible',timeout:20000});assert.match(await page.locator('#trafficClock').innerText(),/תגובת ספק/);
  async function realTrafficPixels(){await page.waitForFunction(()=>Array.from(document.querySelectorAll('.leaflet-traffic-pane img')).some(i=>i.complete&&i.naturalWidth>0),{timeout:20000});return page.locator('.leaflet-traffic-pane img').evaluateAll(images=>{let pixels=0,coloredPixels=0,redPixels=0,orangePixels=0;for(const img of images){if(!img.complete||!img.naturalWidth)continue;const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const c=canvas.getContext('2d');c.drawImage(img,0,0);const data=c.getImageData(0,0,canvas.width,canvas.height).data;for(let i=0;i<data.length;i+=4){const [r,g,b,a]=data.slice(i,i+4);if(a<30)continue;pixels++;if(Math.max(r,g,b)-Math.min(r,g,b)>30)coloredPixels++;if(r>150&&r>g*1.5&&r>b*1.5)redPixels++;if(r>150&&g>75&&g<190&&b<100)orangePixels++;}}return {images:images.filter(i=>i.complete&&i.naturalWidth>0).length,pixels,coloredPixels,redPixels,orangePixels}});}
  const desktopTraffic=await realTrafficPixels();assert.ok(desktopTraffic.coloredPixels>0,'Provider returns real colored traffic pixels, not only configured status or blank tiles');console.log('PUBLIC REAL TOMTOM DESKTOP',JSON.stringify(desktopTraffic));await page.screenshot({path:'dev-public-real-traffic.png'});
  await page.setViewportSize({width:390,height:844});await page.locator('#trafficLegend').waitFor({state:'visible',timeout:20000});const phoneTraffic=await realTrafficPixels();assert.ok(phoneTraffic.coloredPixels>0);console.log('PUBLIC REAL TOMTOM PHONE',JSON.stringify(phoneTraffic));await page.screenshot({path:'dev-public-phone-real-traffic.png'});
  await page.locator('#trafficLayerToggle').click();await page.setViewportSize({width:1440,height:900});
 }
 await page.locator('#placeSearch').fill('23014');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='23014'&&!SafeBusNational.state.busy,{timeout:40000});
}
assert.ok(await page.evaluate(()=>{const s=SafeBusNational.state.station,p=SafeBusNational.state.map.getCenter();return SafeBusNational.state.map.getZoom()>=16&&SafeBusCore.hav([p.lat,p.lng],[s.lat,s.lon])<100}),'Rapid station changes must cancel the previous route framing');
// The following fixtures are deliberately synthetic. They verify UI behavior independent of service hours.
const fixture=await page.evaluate(async()=>{const code='23014',at=new Date(Date.now()-10000).toISOString(),eta=new Date(Date.now()+300000).toISOString(),routes=[],arrivals=[],vehicles=[];for(const [i,line]of ['1','42'].entries()){const f=(await SafeBusDataset.routesFor(line,code))[0],p=f.properties,stop=p.stopSequence.find(s=>s.code===code),coords=f.geometry.coordinates;let nearest=coords[0];for(const c of coords)if(SafeBusCore.hav([c[1],c[0]],[stop.lat,stop.lon])<SafeBusCore.hav([nearest[1],nearest[0]],[stop.lat,stop.lon]))nearest=c;const identity={routeId:String(p.routeId),line,stopCode:code,operatorRef:String(p.agencyId),directionVerified:true,directionEvidence:'exact-line-ref+operator+stop-sequence+destination',sourceObservedAt:at,sourceResponseAt:at,reportedArrivalAt:eta,realtime:true,etaKind:'reported-live',vehicleRef:'fixture'+i,tripId:'fixtureTrip'+i,source:'mot-siri-via-curlbus'};routes.push({routeId:identity.routeId,line,operatorRef:identity.operatorRef,headsign:p.headsign});arrivals.push(identity);vehicles.push({...identity,id:'fixture'+i,lat:nearest[1]+i*.00015,lon:nearest[0]+i*.00015,gpsMeasuredAt:null,clockType:'source-report'})}return {schemaVersion:1,stopCode:code,sourceResponseAt:at,arrivals,vehicles,routes,partial:false}});
Object.assign(fixture.vehicles[0],{source:'open-bus-stride-siri',snapshotAt:fixture.sourceResponseAt,directionVerified:false,directionEvidence:null,bearing:90,reportedSpeedKmh:32,speedUnit:'km/h',speedEvidence:'mot-siri-profile-3.4.56',speedObservedAt:fixture.sourceResponseAt});
const collision={...fixture,routes:[...fixture.routes,{...fixture.routes[0],operatorRef:'987'}],vehicles:[...fixture.vehicles,{...fixture.vehicles[0],operatorRef:'987',vehicleRef:'operator-collision'}]};let mode='fresh',qualityFrame;await page.route('**/api/national?**',route=>{const u=new URL(route.request().url());if(u.searchParams.get('kind')!=='station')return route.continue();if(mode==='failed')return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'SOURCE_UNAVAILABLE'})});const at=new Date(Date.now()-10000).toISOString(),freshFrame=frame=>({...frame,sourceResponseAt:at,arrivals:frame.arrivals.map(a=>({...a,sourceObservedAt:at,sourceResponseAt:at,reportedArrivalAt:new Date(Date.now()+300000).toISOString()})),vehicles:frame.vehicles.map(v=>({...v,sourceObservedAt:at,sourceResponseAt:at,...(v.source==='open-bus-stride-siri'?{snapshotAt:at,speedObservedAt:at}:{})}))});const body=mode==='stale'?{...fixture,sourceResponseAt:'2038-01-01T00:00:00Z'}:mode==='collision'?freshFrame(collision):mode==='quality'?qualityFrame:freshFrame(fixture);return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)})});
await page.route('**/api/live?**',route=>{const u=new URL(route.request().url());if(u.searchParams.get('kind')==='history')return route.continue();return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fixture)})});await page.locator('#stationRefresh').click();await page.waitForFunction(()=>document.querySelectorAll('.bus-marker-label').length===2&&!SafeBusNational.state.busy);assert.equal(await page.locator('.bus-face svg').count(),0,'A map marker contains only the public line and heading arrow');assert.ok(await page.locator('.bus-heading').evaluate(e=>e.getBoundingClientRect().width>=59),'The source arrow is enlarged beyond the 44px hit area');assert.equal(await page.locator('.bus-heading').count(),1,'Only the source-bearing vehicle has an arrow');assert.equal(await page.locator('.bus-heading').evaluate(e=>Math.round(Math.atan2(new DOMMatrix(getComputedStyle(e).transform).b,new DOMMatrix(getComputedStyle(e).transform).a)*180/Math.PI)),90,'An eastward source bearing points right while the line remains upright');assert.equal(await page.locator('.station-arrival').count(),2);assert.ok(await page.locator('.national-stop-pin').count()>0);assert.equal(await page.locator('#nationalFocus').isEnabled(),true);await page.locator('#nationalFocus').click();assert.equal(await page.evaluate(()=>SafeBusNational.visibleTest||SafeBusNational.state.markers.size),2);
await page.evaluate(()=>SafeBusNational.state.markers.values().next().value.openPopup());assert.match(await page.locator('.bus-report').innerText(),/יעד מסלול/);assert.match(await page.locator('.bus-report').innerText(),/32 קמ״ש/);assert.ok(!(await page.locator('.bus-report').innerText()).includes('°'),'Numeric bearing is omitted from text');await page.locator('.bus-source summary').click();assert.match(await page.locator('.bus-source').innerText(),/מפעיל במקור/);assert.match(await page.locator('.bus-source').innerText(),/open-bus-stride-siri/);await page.waitForTimeout(450);assert.ok(await page.locator('.leaflet-popup').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=170&&r.bottom<=innerHeight-25}),'Expanding source details must reposition the popup');assert.ok((await page.locator('.bus-report').innerText()).includes(fixture.routes[0].headsign));assert.equal(await page.locator('.bus-report .report-tags').count(),0,'The popup avoids duplicate technical badges');await page.evaluate(()=>SafeBusNational.state.map.closePopup());

// Synthetic moving bus: an almost-expired original report is replaced by a fresh source frame.
// The open popup must use the new clock, follow the same operator/vehicle and preserve reading/focus.
await page.evaluate(()=>{const v=SafeBusNational.state.stationData.vehicles[0],old=new Date(Date.now()-179000).toISOString();Object.assign(v,{sourceObservedAt:old,snapshotAt:old,speedObservedAt:old});SafeBusNational.renderBuses();const m=SafeBusNational.state.markers.get(v.operatorRef+':'+v.vehicleRef);window.followMarker=m;window.followPopup=m.getPopup();window.followReport=m._reportElement;m.openPopup()});
if(await page.locator('.bus-source').getAttribute('open')===null)await page.locator('.bus-source summary').click();await page.locator('[data-vehicle-history]').focus();
const freshMove=new Date(Date.now()-5000).toISOString();Object.assign(fixture.vehicles[0],{lat:fixture.vehicles[0].lat+.00025,lon:fixture.vehicles[0].lon+.00025,bearing:180,reportedSpeedKmh:0,sourceObservedAt:freshMove,snapshotAt:freshMove,speedObservedAt:freshMove,tripId:'fixtureTrip-new'});
await page.evaluate(()=>SafeBusNational.refreshStation());await page.waitForTimeout(1800);
assert.equal(await page.evaluate(()=>followMarker===SafeBusNational.state.markers.get(followMarker._reportElement.querySelector('[data-vehicle-history]').dataset.operatorRef+':fixture0')&&followMarker.isPopupOpen()&&followMarker.getPopup()===followPopup&&followMarker._reportElement===followReport),true,'Refresh and old-report expiry preserve the same open popup and report DOM');
assert.equal(await page.locator('.bus-source').getAttribute('open'),'','Source details remain expanded through motion');
assert.equal(await page.locator('[data-vehicle-history]').evaluate(e=>e===document.activeElement),true,'The history action retains keyboard focus');
assert.match(await page.locator('.bus-report').innerText(),/0 קמ״ש/);assert.match(await page.locator('.bus-source').innerText(),/fixtureTrip-new/);
assert.equal(await page.evaluate(()=>{const m=followMarker,p=m.getPopup().getLatLng(),v=SafeBusNational.state.stationData.vehicles[0];return p.lat===v.lat&&p.lng===v.lon}),true,'The open bubble follows the reported position');
await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'synthetic-moving-popup-desktop.png'});
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(450);Object.assign(fixture.vehicles[0],{lat:fixture.vehicles[0].lat+.0002,lon:fixture.vehicles[0].lon+.0002,bearing:225});await page.evaluate(()=>SafeBusNational.refreshStation());
assert.equal(await page.evaluate(()=>followMarker.isPopupOpen()&&followPopup.getLatLng().equals(followMarker.getLatLng())),true,'The moving bubble stays attached on a phone');
await page.waitForTimeout(450);assert.ok(await page.locator('.leaflet-popup').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=170&&r.bottom<=innerHeight-25}),'The followed phone popup stays inside the usable map');
await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'synthetic-moving-popup-phone.png'});await page.evaluate(()=>SafeBusNational.state.map.closePopup());await page.setViewportSize({width:1440,height:900});
await page.evaluate(f=>SafeBusNational.previewRoute(f.routes[0].line,f.routes[0].routeId,f.routes[0].operatorRef),fixture);
assert.equal(await page.locator('.bus-marker-label').count(),1,'Bus route preview suppresses other lines at a station');
assert.equal(await page.locator('#stationDock').isVisible(),false,'Other station information does not cover the bus route');
await page.locator('#closeRoutePreview').click();assert.equal(await page.locator('.bus-marker-label').count(),2,'Leaving preview restores other buses');assert.equal(await page.locator('#stationDock').isVisible(),true,'The station returns after route preview');
console.log('SYNTHETIC MOVING POPUP desktop/phone, new trip, new clock, zero speed, heading, source expansion and keyboard focus passed');
await page.locator('#stationLineSelect').selectOption('1');await page.waitForFunction(()=>SafeBusApp.state.route?.properties.line==='1'&&SafeBusNational.state.routeId,{timeout:35000});assert.equal(await page.locator('.bus-marker-label').count(),1);assert.equal(await page.locator('.station-arrival').count(),1);assert.ok(await page.locator('.leaflet-overlay-pane path').count()>0,'The selected route is geographic, not a label');mode='collision';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy);assert.equal(await page.locator('.bus-marker-label').count(),1,'Same route id from another operator must not enter the chosen route');mode='fresh';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy);await page.locator('#stationLineSelect').selectOption('');await page.waitForFunction(()=>document.querySelectorAll('.bus-marker-label').length===2);

// Synthetic ETA update colors: source observation age, not the time remaining to arrival.
const qualityNow=Date.now();qualityFrame={...fixture,sourceResponseAt:new Date(qualityNow-10000).toISOString(),arrivals:[10,90,150].map(age=>({...fixture.arrivals[0],sourceObservedAt:new Date(qualityNow-age*1000).toISOString(),sourceResponseAt:new Date(qualityNow-10000).toISOString()}))};mode='quality';await page.evaluate(()=>SafeBusNational.refreshStation());
assert.deepEqual(await page.locator('.station-arrival').evaluateAll(rows=>rows.map(r=>r.dataset.updateLevel)),['fresh','aging','old']);assert.deepEqual(await page.locator('.arrival-destination small').allTextContents(),['עדכון טרי','מתיישן','עדכון ישן']);
const etaColors=await page.locator('.arrival-time').evaluateAll(rows=>rows.map(r=>getComputedStyle(r).color));assert.equal(new Set(etaColors).size,3,'ETA colors differentiate three source update ages without changing supplier ETA');
await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'synthetic-arrival-colors-desktop.png'});await page.setViewportSize({width:390,height:844});await page.waitForTimeout(450);await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'synthetic-arrival-colors-phone.png'});await page.setViewportSize({width:1440,height:900});mode='fresh';await page.evaluate(()=>SafeBusNational.refreshStation());console.log('SYNTHETIC ARRIVAL UPDATE COLORS green/amber/red passed');
const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const c=canvas.getContext('2d');c.lineWidth=5;for(const [i,color]of ['#39ad57','#efb630','#dd3131'].entries()){c.strokeStyle=color;c.beginPath();c.moveTo(0,80+i*35);c.lineTo(256,100+i*35);c.stroke()}return canvas.toDataURL().split(',')[1]});
const emptyPng=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=256;return canvas.toDataURL().split(',')[1]});
let trafficMode='fresh';await page.route('**/api/traffic?**',route=>{const u=new URL(route.request().url());return u.searchParams.get('kind')==='status'?route.fulfill({status:200,contentType:'application/json',body:'{"available":true,"provider":"TomTom"}'}):trafficMode==='unavailable'?route.fulfill({status:503,contentType:'application/json',body:'{"error":"TRAFFIC_UNAVAILABLE"}'}):trafficMode==='failed'?route.fulfill({status:429,contentType:'application/json',body:'{"error":"TRAFFIC_QUOTA_EXHAUSTED"}'}):route.fulfill({status:200,contentType:'image/png',headers:{'X-Traffic-Originated-At':new Date(Date.now()-(trafficMode==='stale'?190000:10000)).toISOString(),'X-Traffic-Retrieved-At':new Date().toISOString(),'X-Traffic-Source-Age':'0','X-Traffic-Clock':'provider-response'},body:Buffer.from(trafficMode==='empty'?emptyPng:png,'base64')})});await page.locator('#trafficLayerToggle').click();await page.locator('#trafficLegend').waitFor({state:'visible'});assert.ok(await page.locator('.leaflet-traffic-pane img').count()>0,'Traffic tiles must be on the bus map');assert.equal(await page.locator('.bus-marker-label').count(),2);assert.equal(page.url(),base+'/');await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'synthetic-combined.png'});await page.locator('#trafficLayerToggle').click();assert.equal(await page.locator('#trafficLegend').isVisible(),false);assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);

// Explicit synthetic empty and failed tiles: a valid transparent PNG never means active traffic.
trafficMode='empty';await page.locator('#trafficLayerToggle').click();await page.waitForFunction(()=>!SafeBusNational.state.trafficEnabled&&SafeBusNational.state.trafficStatus==='no-data',null,{timeout:20000});assert.equal(await page.locator('#trafficLegend').isVisible(),false);assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);assert.match(await page.locator('#trafficLayerNote').innerText(),/אין נתונים/);
trafficMode='unavailable';await page.locator('#trafficLayerToggle').click();await page.waitForFunction(()=>!SafeBusNational.state.trafficEnabled&&SafeBusNational.state.trafficStatus==='unavailable');assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);assert.match(await page.locator('#notice').innerText(),/אינם זמינים/);
// Explicit synthetic tile faults: one successful image must not hide stale or quota failures.
trafficMode='stale';await page.locator('#trafficLayerToggle').click();await page.waitForFunction(()=>!document.getElementById('trafficLayerToggle').disabled&&!SafeBusNational.state.trafficEnabled&&document.getElementById('notice').textContent.includes('תוקף'));assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);assert.match(await page.locator('#notice').innerText(),/תוקף/);
trafficMode='fresh';await page.locator('#trafficLayerToggle').click();await page.locator('#trafficLegend').waitFor({state:'visible'});trafficMode='failed';await page.evaluate(()=>SafeBusNational.state.traffic.redraw());await page.waitForFunction(()=>!SafeBusNational.state.trafficEnabled);assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);assert.match(await page.locator('#notice').innerText(),/מכסת/);
trafficMode='fresh';
await page.evaluate(()=>{const s=SafeBusNational.state.station;SafeBusNational.state.map.setView([s.lat,s.lon],17,{animate:false});SafeBusNational.renderStops()});await page.locator('#stationsToggle').click();assert.equal(await page.locator('.national-stop-pin').count(),0);await page.locator('#stationsToggle').click();assert.ok(await page.locator('.national-stop-pin').count()>0);await page.locator('#busesToggle').click();assert.equal(await page.locator('.bus-marker-label').count(),0);await page.locator('#busesToggle').click();assert.equal(await page.locator('.bus-marker-label').count(),2);
mode='stale';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy&&SafeBusNational.state.stationData?.arrivals.length===0);assert.equal(await page.locator('.bus-marker-label').count(),0);assert.equal(await page.locator('.station-arrival').count(),0);mode='failed';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy&&SafeBusNational.state.stationError);assert.match(await page.locator('#stationArrivals').innerText(),/לא ניתן לקבל/);
mode='fresh';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy&&SafeBusNational.state.markers.size===2);await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await page.locator('#map').evaluate(e=>e.getBoundingClientRect().height),844);assert.ok(await page.locator('#stationDock').evaluate(e=>e.getBoundingClientRect().height<=844*.44));await page.evaluate(f=>{SafeBusNational.state.map.setView([f.vehicles[0].lat,f.vehicles[0].lon],17,{animate:false});SafeBusNational.renderBuses()},fixture);await page.locator('.bus-pin').first().click();await page.locator('.bus-report').waitFor({state:'visible'});await page.locator('.bus-source summary').click();await page.waitForTimeout(450);assert.ok(await page.locator('.leaflet-popup').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=170&&r.bottom<=innerHeight-25}),'Phone popup expansion must remain within the screen');await page.evaluate(()=>SafeBusNational.state.map.closePopup());await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'phone.png'});await page.locator('#dockToggle').click();assert.equal(await page.locator('#stationBody').isVisible(),false);await page.locator('#closeStation').click();assert.equal(await page.locator('#stationDock').isVisible(),false);await page.evaluate(f=>SafeBusNational.previewRoute(f.routes[0].line,f.routes[0].routeId,f.routes[0].operatorRef),fixture);await page.locator('#routePreview').waitFor({state:'visible'});assert.match(await page.locator('#routePreviewNote').innerText(),/מסלול מתוכנן/);await page.locator('#closeRoutePreview').click();await page.locator('#countryView').click();assert.ok(await page.evaluate(()=>SafeBusNational.state.map.getBounds().getSouth()<30));
await page.locator('#settingsOpen').click();await page.locator('#settingsClose').waitFor({state:'visible'});assert.equal(await page.locator('#settingsOpen').getAttribute('aria-label'),'הגדרות ומקורות');assert.equal(await page.locator('#settingsOpen svg').count(),1);assert.equal(await page.locator('.national-app').evaluate(e=>e.inert),true);assert.equal(await page.locator('#trafficAccountLink').getAttribute('href'),'https://my.tomtom.com/');assert.match(await page.locator('.service-connections').innerText(),/ללא חשבון אישי/);await page.waitForFunction(()=>document.getElementById('trafficConnectionStatus').textContent.includes('מחובר'),null,{timeout:10000});await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'settings.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('#panel').isVisible(),false);assert.equal(await page.locator('.national-app').evaluate(e=>e.inert),false);
// Synthetic area continuity: pan/request delay, partial response, failure, then original-clock expiry.
await page.setViewportSize({width:1440,height:900});
let areaMode='full',releaseArea,areaStarted;
const areaSeen=new Promise(resolve=>areaStarted=resolve),areaHold=new Promise(resolve=>releaseArea=resolve);
await page.route('**/api/national?**',async route=>{
 const u=new URL(route.request().url());if(u.searchParams.get('kind')!=='area')return route.fallback();
 const bbox=u.searchParams.get('bbox').split(',').map(Number);
 if(areaMode==='failed')return route.fulfill({status:503,contentType:'application/json',body:'{"error":"SOURCE_UNAVAILABLE"}'});
 if(areaMode==='delayed'){areaStarted();await areaHold;}
 const at=new Date(Date.now()-10000).toISOString(),base={...fixture.vehicles[0],sourceObservedAt:at,sourceResponseAt:at,snapshotAt:at,speedObservedAt:at};
 const center={lat:(bbox[1]+bbox[3])/2,lon:(bbox[0]+bbox[2])/2};
 const rows=[{...base,...center,vehicleRef:'area-one',tripId:'area-trip-one'},{...base,...center,lat:center.lat+.0001,vehicleRef:'area-two',tripId:'area-trip-two'}];
 const body={schemaVersion:1,bbox,sourceResponseAt:at,coverage:'open-bus-stride-siri',vehicles:areaMode==='full'?rows:[{...rows[0],lon:center.lon+.0002,tripId:'area-trip-updated'}]};
 return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
});
await page.evaluate(f=>SafeBusNational.state.map.setView([f.vehicles[0].lat,f.vehicles[0].lon],16,{animate:false}),fixture);
await page.waitForFunction(()=>!SafeBusNational.state.busy&&SafeBusNational.state.markers.size===2,null,{timeout:25000});
const retainedClock=await page.evaluate(()=>{const m=SafeBusNational.state.markers.values().next().value;m.openPopup();window.areaFollowPopup=m.getPopup();window.areaFollowMarker=m;window.areaMarkerElements=[...SafeBusNational.state.markers.values()].map(m=>m.getElement());return SafeBusNational.state.areaData.vehicles.find(v=>v.vehicleRef==='area-two').sourceObservedAt});
areaMode='delayed';await page.evaluate(()=>SafeBusNational.state.map.panBy([8,0],{animate:false}));await areaSeen;
assert.equal(await page.locator('.bus-marker-label').count(),2,'Panning and a pending request retain both current reports');
assert.equal(await page.evaluate(()=>areaMarkerElements.every(e=>e.isConnected)),true,'Existing marker DOM remains attached during refresh');
releaseArea();await page.waitForFunction(()=>!SafeBusNational.state.busy&&SafeBusNational.state.areaData.vehicles.some(v=>v.tripId==='area-trip-updated'));
assert.equal(await page.locator('.bus-marker-label').count(),2,'A partial response retains the absent fresh report');assert.equal(await page.evaluate(()=>areaFollowMarker.isPopupOpen()&&areaFollowPopup.getLatLng().equals(areaFollowMarker.getLatLng())),true,'Area refresh follows the selected bus through partial frames');
assert.equal(await page.evaluate(()=>SafeBusNational.state.areaData.vehicles.find(v=>v.vehicleRef==='area-two').sourceObservedAt),retainedClock);

// Same route id from a different operator and a different line are irrelevant during bus route preview.
await page.evaluate(f=>{const s=SafeBusNational.state,a=s.areaData.vehicles[0],at=new Date(Date.now()-5000).toISOString();s.areaData.vehicles.push({...a,operatorRef:'987',vehicleRef:'route-operator-collision'},{...f.vehicles[1],lat:a.lat+.0003,lon:a.lon+.0003,sourceObservedAt:at,sourceResponseAt:at});SafeBusNational.renderBuses()},fixture);
assert.equal(await page.locator('.bus-marker-label').count(),4);
await page.evaluate(f=>SafeBusNational.previewRoute(f.routes[0].line,f.routes[0].routeId,f.routes[0].operatorRef),fixture);
assert.equal(await page.locator('.bus-marker-label').count(),2,'Area preview keeps only the exact operator and route');assert.equal(await page.evaluate(()=>[...SafeBusNational.state.markers.keys()].some(k=>k.startsWith('987:'))),false);
await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'synthetic-route-focus.png'});await page.locator('#closeRoutePreview').click();assert.equal(await page.locator('.bus-marker-label').count(),4,'Exit restores other operator and line reports');
await page.evaluate(()=>{SafeBusNational.state.areaData.vehicles=SafeBusNational.state.areaData.vehicles.filter(v=>v.vehicleRef.startsWith('area-'));SafeBusNational.renderBuses();areaFollowMarker.openPopup()});
areaMode='failed';await page.evaluate(()=>SafeBusNational.refreshArea());assert.equal(await page.locator('.bus-marker-label').count(),2,'Transient area failure does not erase recent observations');assert.match(await page.locator('#nationalBusCount').innerText(),/רענון חסר/);
await page.evaluate(()=>{const old=new Date(Date.now()-181000).toISOString();for(const v of SafeBusNational.state.areaData.vehicles){v.sourceObservedAt=old;v.snapshotAt=old;}SafeBusNational.renderBuses()});
assert.equal(await page.locator('.bus-marker-label').count(),0,'Expired original observations are removed even after failure');assert.equal(await page.locator('.bus-report').count(),0,'An open popup closes only when its actual current observation expires');
await page.locator('#countryView').click();

// Synthetic traffic is enabled on opening; a user's off preference survives reload.
await page.evaluate(()=>localStorage.removeItem('eifo-traffic-preference'));await page.reload({waitUntil:'domcontentloaded'});await page.locator('#trafficLegend').waitFor({state:'visible',timeout:40000});assert.equal(await page.locator('#trafficLayerToggle').getAttribute('aria-pressed'),'true','Traffic defaults on when a configured provider returns fresh images');await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'phone-default-traffic-synthetic.png'});await page.locator('#trafficLayerToggle').click();await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>SafeBusNational.state.ready);assert.equal(await page.evaluate(()=>SafeBusNational.state.trafficWanted),false);assert.equal(await page.locator('#trafficLegend').isVisible(),false);
// Diagnostics must describe the current map, never the hidden 72/2360 defaults.
await page.locator('#settingsOpen').click();await page.locator('#systemDetails summary').click();await page.locator('#diagnose').click();await page.waitForFunction(()=>!document.getElementById('diagnose').disabled,{timeout:45000});const diagnostic=await page.locator('#diagnostic').innerText();assert.match(diagnostic,/אזור המפה · ללא תחנה נבחרת/);assert.ok(!diagnostic.includes('קו 72')&&!diagnostic.includes('תחנה 2360'));assert.ok(!diagnostic.includes('אין שגיאה מדווחת'));await page.screenshot({path:(publicBase?'dev-public-':'dev-national-')+'phone-diagnostics.png'});await page.keyboard.press('Escape');
assert.deepEqual(errors,[]);
console.log('PASS: real national address/stop flow plus explicit synthetic combined-map traffic, buses, lines, controls, expired reports, provider failure and responsive screen use');
}catch(e){if(debugPage){console.log('BROWSER FAILURE GEOMETRY',JSON.stringify(await debugPage.evaluate(()=>{const rect=s=>{const e=document.querySelector(s);if(!e)return null;const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};return {popup:rect('.leaflet-popup'),report:rect('.bus-report'),summary:rect('.bus-source summary'),map:rect('#map'),viewport:[innerWidth,innerHeight],center:window.SafeBusNational?.state.map?.getCenter(),popupPanning:window.SafeBusNational?.state.popupPanning,markers:window.SafeBusNational?.state.markers.size}})));await debugPage.screenshot({path:(process.env.DEV_BASE_URL?'dev-public-':'dev-national-')+'failure.png'});}throw e;}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
