'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),http=require('node:http'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const root=path.resolve(__dirname,'..'),folder=path.join(root,'dist'),handlers={};for(const name of ['live','national','dataset','search','traffic'])handlers[name]=(await import(pathToFileURL(path.join(root,'api/'+name+'.mjs')).href)).GET;const security=JSON.parse(await fs.readFile(path.join(root,'vercel.json'),'utf8')).headers[0].headers;
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://127.0.0.1');if(url.pathname.startsWith('/api/')){const handler=handlers[url.pathname.slice(5)];if(!handler){res.writeHead(404);res.end();return;}const r=await handler(new Request(url));res.writeHead(r.status,Object.fromEntries(r.headers));res.end(Buffer.from(await r.arrayBuffer()));return;}const file=path.resolve(folder,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(folder+path.sep)){res.writeHead(403);res.end();return;}const data=await fs.readFile(file),type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'}[path.extname(file)]||'application/octet-stream';res.writeHead(200,{'Content-Type':type,...Object.fromEntries(security.map(h=>[h.key,h.value]))});res.end(data)}catch{res.writeHead(404);res.end('Unavailable')}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
let debugPage;try{const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],searchCalls=[];debugPage=page;page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('BROWSER CONSOLE ERROR',m.text())});page.on('request',r=>{if(r.url().includes('/api/search?'))searchCalls.push(r.url())});const publicBase=process.env.DEV_BASE_URL;if(publicBase&&publicBase!=='https://eifo-batuach-dev.vercel.app')throw Error('Public QA is restricted to the canonical DEV site');const base=publicBase||'http://127.0.0.1:'+server.address().port;const response=await page.goto(base,{waitUntil:'domcontentloaded'});assert.match(response.headers()['content-security-policy'],/script-src 'self'/);await page.waitForFunction(()=>SafeBusNational.state.ready,{timeout:40000});assert.ok(await page.evaluate(()=>SafeBusNational.state.stops.length>20000));assert.equal(await page.evaluate(()=>SafeBusApp.state.route),null,'Countrywide opening must not silently select Gila');
const size=await page.locator('#map').evaluate(e=>({width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height}));assert.deepEqual(size,{width:1440,height:900});await page.screenshot({path:(publicBase?'dev-public-':'')+'dev-national-country.png'});
for(const query of ['רוטשילד תל אביב','מרכז חורב חיפה','אילת']){const before=searchCalls.length;await page.locator('#placeSearch').fill(query);await page.waitForTimeout(250);assert.equal(searchCalls.length,before,'Typing searches the local catalog; geocoder is explicit-submit only');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>!document.getElementById('searchSubmit').disabled,{timeout:30000});const places=page.locator('#searchResults li button').filter({hasText:'OpenStreetMap'});assert.ok(await places.count(),'Real address search must return places for '+query);await places.first().click();const p=await page.evaluate(()=>SafeBusNational.state.map.getCenter());assert.ok(p.lat>=29&&p.lat<=34&&p.lng>=34&&p.lng<=36);console.log('REAL NATIONAL ADDRESS',query,JSON.stringify(p));await page.waitForTimeout(1200)}
await page.locator('#placeSearch').fill('23014');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='23014'&&!SafeBusNational.state.busy,{timeout:40000});assert.equal(await page.evaluate(()=>SafeBusNational.state.stationError),null);assert.ok(await page.locator('#stationLineSelect option').count()>20);console.log('REAL NATIONAL STATION',JSON.stringify(await page.evaluate(()=>({code:SafeBusNational.state.station.code,arrivals:SafeBusNational.state.stationData.arrivals.length,vehicles:SafeBusNational.state.stationData.vehicles.length,partial:SafeBusNational.state.stationData.partial}))));
await page.locator('#placeSearch').fill('3441');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='3441'&&!SafeBusNational.state.busy,{timeout:40000});await page.locator('#stationLineSelect').selectOption('10א');await page.waitForFunction(()=>SafeBusApp.state.route?.properties.line==='10א'&&SafeBusNational.state.routeId,{timeout:35000});assert.ok(await page.locator('.leaflet-overlay-pane path').count()>0,'Hebrew line suffix loads its real national GTFS route');console.log('REAL HEBREW-SUFFIX ROUTE',JSON.stringify(await page.evaluate(()=>({line:SafeBusApp.state.route.properties.line,points:SafeBusApp.state.route.geometry.coordinates.length}))));await page.locator('#placeSearch').fill('23014');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='23014'&&!SafeBusNational.state.busy,{timeout:40000});
if(publicBase){
 const deployed=await (await page.request.get(base+'/deployment.json')).json();assert.equal(deployed.version,'DEV-9.2.1');assert.equal(deployed.branch,'dev/vehicle-history-map-20261009');
 assert.equal(await page.locator('html').getAttribute('dir'),'rtl');console.log('PUBLIC REAL DEPLOYMENT',JSON.stringify(deployed));
 await page.locator('#closeStation').click();
 let realBuses=0;
 for(const query of ['מרכז חורב חיפה','נצרת']){
  await page.locator('#placeSearch').fill(query);await page.locator('#searchSubmit').click();await page.waitForFunction(()=>!document.getElementById('searchSubmit').disabled&&!document.getElementById('searchResults').textContent.includes('מחפש כתובות'),{timeout:30000});
  const places=page.locator('#searchResults li button').filter({hasText:'OpenStreetMap'});if(!await places.count()){console.log('PUBLIC REAL AREA NOT FOUND',query);continue;}await places.first().click();
  await page.waitForTimeout(1300);await page.waitForFunction(()=>!SafeBusNational.state.busy,{timeout:45000});
  const report=await page.evaluate(()=>({error:SafeBusNational.state.areaError,rawCount:SafeBusNational.state.areaData?.vehicles?.length||0,shown:SafeBusNational.state.markers.size,source:SafeBusNational.state.areaData?.coverage,vehicles:(SafeBusNational.state.areaData?.vehicles||[]).slice(0,3)}));
  realBuses+=report.shown;console.log('PUBLIC REAL AREA',query,JSON.stringify(report));
  if(report.shown){
   await page.locator('.bus-pin').first().click();await page.locator('.bus-report').waitFor({state:'visible'});await page.locator('.bus-source summary').click();await page.evaluate(()=>SafeBusNational.renderBuses());assert.equal(await page.locator('.bus-source').evaluate(e=>e.open),true,'Refreshing ages must preserve expanded report details');assert.match(await page.locator('.bus-report').innerText(),/זמן דיווח/);
   await page.screenshot({path:'dev-public-real-bus.png'});
   const route=page.locator('.bus-report [data-bus-route]');if(await route.count()){await route.click();await page.locator('#routePreview').waitFor({state:'visible'});assert.ok(await page.locator('.leaflet-overlay-pane path').count()>0);await page.locator('#closeRoutePreview').click();}
   await page.evaluate(()=>SafeBusNational.state.map.closePopup());
  }
 }
 console.log('PUBLIC REAL BUS MARKERS OBSERVED',realBuses,'Zero means actual marker flow was not witnessed; synthetic tests below do not substitute for it.');
 const realTraffic=await (await page.request.get(base+'/api/traffic?kind=status')).json();console.log('PUBLIC REAL TRAFFIC STATUS',JSON.stringify(realTraffic));
 if(!realTraffic.available){await page.locator('#trafficLayerToggle').click();await page.waitForFunction(()=>!document.getElementById('trafficLayerToggle').disabled);assert.equal(await page.locator('#trafficLegend').isVisible(),false);assert.match(await page.locator('#notice').innerText(),/ממתינה/);}
 else {await page.locator('#trafficLayerToggle').click();await page.locator('#trafficLegend').waitFor({state:'visible',timeout:20000});assert.match(await page.locator('#trafficClock').innerText(),/תגובת ספק/);await page.screenshot({path:'dev-public-real-traffic.png'});await page.locator('#trafficLayerToggle').click();}
 await page.locator('#placeSearch').fill('23014');await page.locator('#searchSubmit').click();await page.waitForFunction(()=>SafeBusNational.state.station?.code==='23014'&&!SafeBusNational.state.busy,{timeout:40000});
}
// The following fixtures are deliberately synthetic. They verify UI behavior independent of service hours.
const fixture=await page.evaluate(async()=>{const code='23014',at=new Date(Date.now()-10000).toISOString(),eta=new Date(Date.now()+300000).toISOString(),routes=[],arrivals=[],vehicles=[];for(const [i,line]of ['1','42'].entries()){const f=(await SafeBusDataset.routesFor(line,code))[0],p=f.properties,stop=p.stopSequence.find(s=>s.code===code),coords=f.geometry.coordinates;let nearest=coords[0];for(const c of coords)if(SafeBusCore.hav([c[1],c[0]],[stop.lat,stop.lon])<SafeBusCore.hav([nearest[1],nearest[0]],[stop.lat,stop.lon]))nearest=c;const identity={routeId:String(p.routeId),line,stopCode:code,operatorRef:String(p.agencyId),directionVerified:true,directionEvidence:'exact-line-ref+operator+stop-sequence+destination',sourceObservedAt:at,sourceResponseAt:at,reportedArrivalAt:eta,realtime:true,etaKind:'reported-live',vehicleRef:'fixture'+i,tripId:'fixtureTrip'+i,source:'mot-siri-via-curlbus'};routes.push({routeId:identity.routeId,line,operatorRef:identity.operatorRef,headsign:p.headsign});arrivals.push(identity);vehicles.push({...identity,id:'fixture'+i,lat:nearest[1]+i*.00015,lon:nearest[0]+i*.00015,gpsMeasuredAt:null,clockType:'source-report'})}return {schemaVersion:1,stopCode:code,sourceResponseAt:at,arrivals,vehicles,routes,partial:false}});
Object.assign(fixture.vehicles[0],{source:'open-bus-stride-siri',snapshotAt:fixture.sourceResponseAt,directionVerified:false,directionEvidence:null,reportedSpeedKmh:32,speedUnit:'km/h',speedEvidence:'mot-siri-profile-3.4.56',speedObservedAt:fixture.sourceResponseAt});
const collision={...fixture,routes:[...fixture.routes,{...fixture.routes[0],operatorRef:'987'}],vehicles:[...fixture.vehicles,{...fixture.vehicles[0],operatorRef:'987',vehicleRef:'operator-collision'}]};let mode='fresh';await page.route('**/api/national?**',route=>{const u=new URL(route.request().url());if(u.searchParams.get('kind')!=='station')return route.continue();if(mode==='failed')return route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'SOURCE_UNAVAILABLE'})});const body=mode==='stale'?{...fixture,sourceResponseAt:'2038-01-01T00:00:00Z'}:mode==='collision'?collision:fixture;return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)})});
await page.route('**/api/live?**',route=>{const u=new URL(route.request().url());if(u.searchParams.get('kind')==='history')return route.continue();return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(fixture)})});await page.locator('#stationRefresh').click();await page.waitForFunction(()=>document.querySelectorAll('.bus-face svg').length===2&&!SafeBusNational.state.busy);assert.equal(await page.locator('.station-arrival').count(),2);assert.ok(await page.locator('.national-stop-dot').count()>0);assert.equal(await page.locator('#nationalFocus').isEnabled(),true);await page.locator('#nationalFocus').click();assert.equal(await page.evaluate(()=>SafeBusNational.visibleTest||SafeBusNational.state.markers.size),2);
await page.evaluate(()=>SafeBusNational.state.markers.values().next().value.openPopup());assert.match(await page.locator('.bus-report').innerText(),/יעד המסלול/);assert.match(await page.locator('.bus-report').innerText(),/32 קמ״ש/);await page.locator('.bus-source summary').click();assert.match(await page.locator('.bus-source').innerText(),/מפעיל במקור/);assert.match(await page.locator('.bus-source').innerText(),/open-bus-stride-siri/);assert.ok((await page.locator('.bus-report').innerText()).includes(fixture.routes[0].headsign));assert.match(await page.locator('.bus-report').innerText(),/יעד הנסיעה וזמן ההגעה אינם מאומתים/);await page.evaluate(()=>SafeBusNational.state.map.closePopup());
await page.locator('#stationLineSelect').selectOption('1');await page.waitForFunction(()=>SafeBusApp.state.route?.properties.line==='1'&&SafeBusNational.state.routeId,{timeout:35000});assert.equal(await page.locator('.bus-face svg').count(),1);assert.equal(await page.locator('.station-arrival').count(),1);assert.ok(await page.locator('.leaflet-overlay-pane path').count()>0,'The selected route is geographic, not a label');mode='collision';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy);assert.equal(await page.locator('.bus-face svg').count(),1,'Same route id from another operator must not enter the chosen route');mode='fresh';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy);await page.locator('#stationLineSelect').selectOption('');await page.waitForFunction(()=>document.querySelectorAll('.bus-face svg').length===2);
const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const c=canvas.getContext('2d');c.lineWidth=5;for(const [i,color]of ['#39ad57','#efb630','#dd3131'].entries()){c.strokeStyle=color;c.beginPath();c.moveTo(0,80+i*35);c.lineTo(256,100+i*35);c.stroke()}return canvas.toDataURL().split(',')[1]});
let trafficMode='fresh';await page.route('**/api/traffic?**',route=>{const u=new URL(route.request().url());return u.searchParams.get('kind')==='status'?route.fulfill({status:200,contentType:'application/json',body:'{"available":true,"provider":"TomTom"}'}):trafficMode==='failed'?route.fulfill({status:429,contentType:'application/json',body:'{"error":"TRAFFIC_QUOTA_EXHAUSTED"}'}):route.fulfill({status:200,contentType:'image/png',headers:{'X-Traffic-Originated-At':new Date(Date.now()-(trafficMode==='stale'?190000:10000)).toISOString(),'X-Traffic-Retrieved-At':new Date().toISOString(),'X-Traffic-Source-Age':'0','X-Traffic-Clock':'provider-response'},body:Buffer.from(png,'base64')})});await page.locator('#trafficLayerToggle').click();await page.locator('#trafficLegend').waitFor({state:'visible'});assert.ok(await page.locator('.leaflet-traffic-pane img').count()>0,'Traffic tiles must be on the bus map');assert.equal(await page.locator('.bus-face svg').count(),2);assert.equal(page.url(),base+'/');await page.screenshot({path:'dev-national-synthetic-combined.png'});await page.locator('#trafficLayerToggle').click();assert.equal(await page.locator('#trafficLegend').isVisible(),false);assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);

// Explicit synthetic tile faults: one successful image must not hide stale or quota failures.
trafficMode='stale';await page.locator('#trafficLayerToggle').click();await page.waitForFunction(()=>!document.getElementById('trafficLayerToggle').disabled&&!SafeBusNational.state.trafficEnabled&&document.getElementById('notice').textContent.includes('תוקף'));assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);assert.match(await page.locator('#notice').innerText(),/תוקף/);
trafficMode='fresh';await page.locator('#trafficLayerToggle').click();await page.locator('#trafficLegend').waitFor({state:'visible'});trafficMode='failed';await page.evaluate(()=>SafeBusNational.state.traffic.redraw());await page.waitForFunction(()=>!SafeBusNational.state.trafficEnabled);assert.equal(await page.locator('.leaflet-traffic-pane img').count(),0);assert.match(await page.locator('#notice').innerText(),/מכסת/);
trafficMode='fresh';
await page.locator('#stationsToggle').click();assert.equal(await page.locator('.national-stop-dot').count(),0);await page.locator('#stationsToggle').click();assert.ok(await page.locator('.national-stop-dot').count()>0);await page.locator('#busesToggle').click();assert.equal(await page.locator('.bus-face svg').count(),0);await page.locator('#busesToggle').click();assert.equal(await page.locator('.bus-face svg').count(),2);
mode='stale';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy&&SafeBusNational.state.stationData?.arrivals.length===0);assert.equal(await page.locator('.bus-face svg').count(),0);assert.equal(await page.locator('.station-arrival').count(),0);mode='failed';await page.locator('#stationRefresh').click();await page.waitForFunction(()=>!SafeBusNational.state.busy&&SafeBusNational.state.stationError);assert.match(await page.locator('#stationArrivals').innerText(),/לא ניתן לקבל/);
await page.setViewportSize({width:390,height:844});await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.equal(await page.locator('#map').evaluate(e=>e.getBoundingClientRect().height),844);assert.ok(await page.locator('#stationDock').evaluate(e=>e.getBoundingClientRect().height<=844*.44));await page.screenshot({path:'dev-national-phone.png'});await page.locator('#dockToggle').click();assert.equal(await page.locator('#stationBody').isVisible(),false);await page.locator('#closeStation').click();assert.equal(await page.locator('#stationDock').isVisible(),false);await page.evaluate(f=>SafeBusNational.previewRoute(f.routes[0].line,f.routes[0].routeId,f.routes[0].operatorRef),fixture);await page.locator('#routePreview').waitFor({state:'visible'});assert.match(await page.locator('#routePreviewNote').innerText(),/כיוון נסיעת הרכב לא אומת/);await page.locator('#closeRoutePreview').click();await page.locator('#countryView').click();assert.ok(await page.evaluate(()=>SafeBusNational.state.map.getBounds().getSouth()<30));
await page.locator('#settingsOpen').click();await page.locator('#settingsClose').waitFor({state:'visible'});assert.match(await page.locator('#settingsOpen').innerText(),/הגדרות/);assert.equal(await page.locator('#trafficAccountLink').getAttribute('href'),'https://my.tomtom.com/');assert.match(await page.locator('.service-connections').innerText(),/ללא חשבון אישי/);await page.waitForFunction(()=>document.getElementById('trafficConnectionStatus').textContent.includes('החיבור מוגדר'),null,{timeout:10000});await page.screenshot({path:'dev-national-settings.png'});await page.keyboard.press('Escape');assert.equal(await page.locator('#panel').isVisible(),false);assert.deepEqual(errors,[]);
console.log('PASS: real national address/stop flow plus explicit synthetic combined-map traffic, buses, lines, controls, expired reports, provider failure and responsive screen use');
}catch(e){if(debugPage){console.log('BROWSER FAILURE GEOMETRY',JSON.stringify(await debugPage.evaluate(()=>{const rect=s=>{const e=document.querySelector(s);if(!e)return null;const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height}};return {popup:rect('.leaflet-popup'),report:rect('.bus-report'),summary:rect('.bus-source summary'),map:rect('#map'),viewport:[innerWidth,innerHeight],center:SafeBusNational.state.map.getCenter(),popupPanning:SafeBusNational.state.popupPanning,markers:SafeBusNational.state.markers.size}})));await debugPage.screenshot({path:'dev-national-failure.png'});}throw e;}finally{await browser.close();await new Promise(r=>server.close(r))}})().catch(e=>{console.error(e);process.exitCode=1});
