'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
(async()=>{const {normalizeArea,validBBox,createNationalProviders}=await import('../backend/national/providers.mjs');const now=Date.parse('2026-10-09T13:10:30Z'),bbox=[34.75,32.03,34.85,32.12],row={id:1,recorded_at_time:'2026-10-09T13:10:15Z',siri_snapshot__snapshot_id:'2026/10/09/13/10',lon:34.79,lat:32.08,siri_route__operator_ref:15,siri_route__line_ref:23397,siri_ride__id:123,siri_ride__vehicle_ref:'100',bearing:45};
assert.equal(normalizeArea([row,row],bbox,now).vehicles.length,1);for(const change of [{recorded_at_time:'2038-01-14T17:22:21Z'},{siri_snapshot__snapshot_id:'2026/03/19/19/26'},{recorded_at_time:'2026-10-09T12:00:00Z'},{lon:35.2},{siri_ride__vehicle_ref:null},{siri_route__operator_ref:null}])assert.equal(normalizeArea([{...row,...change}],bbox,now).vehicles.length,0,JSON.stringify(change));
assert.equal(normalizeArea([row,{...row,siri_route__operator_ref:3}],bbox,now).vehicles.length,2,'Vehicle identities are scoped by operator');assert.equal(validBBox([34,29,36,34]),false);assert.equal(validBBox(bbox),true);
const window={},ctx={window,Date,Number,String,Map,console};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../national-contract.js'),'utf8'),ctx);const N=window.SafeBusNationalContract,vehicle=normalizeArea([row],bbox,now).vehicles[0];assert.equal(N.area({schemaVersion:1,bbox,vehicles:[vehicle]},bbox,{now}).vehicles.length,1);assert.equal(N.vehicles([{...vehicle,gpsMeasuredAt:new Date(now).toISOString()}],{now}).length,0);assert.throws(()=>N.area({schemaVersion:1,bbox:[34,30,35,31],vehicles:[]},bbox));
for(const speed of [0,32,160]){const v=normalizeArea([{...row,velocity:speed}],bbox,now).vehicles[0];assert.equal(v.reportedSpeedKmh,speed,'MOT velocity is already km/h; zero is valid');assert.equal(N.vehicles([v],{now})[0].reportedSpeedKmh,speed);assert.equal(N.vehicles([v],{now})[0].velocity,null,'Reported speed must not become independent GPS evidence');}
for(const speed of [-1,161,'32',null,undefined,NaN,Infinity])assert.equal(normalizeArea([{...row,velocity:speed}],bbox,now).vehicles[0].reportedSpeedKmh,null);
const fast=normalizeArea([{...row,velocity:32}],bbox,now).vehicles[0];for(const change of [{speedUnit:'m/s'},{speedEvidence:null},{speedObservedAt:new Date(now).toISOString()},{reportedSpeedKmh:161}])assert.equal(N.vehicles([{...fast,...change}],{now})[0].reportedSpeedKmh,null);
const destinations=[{operatorRef:'15',routeId:'23397',line:'5',headsign:'יעד א'},{operatorRef:'3',routeId:'23397',line:'5',headsign:'יעד אחר'}];assert.equal(N.routeMeta(vehicle,destinations).headsign,'יעד א');assert.equal(N.routeMeta({...vehicle,operatorRef:'97'},destinations),null,'Shared route numbers do not establish a destination across operators');assert.equal(N.routeMeta(vehicle,[],{'15:23397':{headsign:'יעד האינדקס'}}).headsign,'יעד האינדקס');
const stops=[{code:'200',name:'תחנה חיפה',search:N.fold('תחנה חיפה 200'),lat:32.8,lon:35},{code:'300',name:'תחנה אילת',search:N.fold('תחנה אילת 300'),lat:29.6,lon:34.95}];assert.equal(N.stopSearch(stops,'אילת')[0].code,'300');assert.equal(N.stopSearch(stops,'200')[0].code,'200');
const {decodePolyline}=await import('../backend/national/geometry.mjs');function encode(points){let a=0,b=0,out='';for(const [lon,lat]of points){const x=Math.round(lat*1e6),y=Math.round(lon*1e6);for(const delta of [x-a,y-b]){let n=delta<0?~(delta<<1):delta<<1;while(n>=32){out+=String.fromCharCode((32|(n&31))+63);n>>=5}out+=String.fromCharCode(n+63)}a=x;b=y}return out}
const shape=encode([[34.79,32.08],[34.8,32.09],[34.81,32.1]]);assert.equal(decodePolyline(shape).length,3);const station='20000',catalog={schema:2,stops:{[station]:[32.08,34.79,'תל אביב'],30000:[32.1,34.81,'יעד']},served:{[station]:['5','18']}};
const source={timestamp:new Date(now-1000).toISOString(),visits:{[station]:['5','18'].map((line,i)=>({stop_code:station,line_name:line,line_id:String(101+i),operator_id:15,destination_id:'30000',timestamp:new Date(now-5000).toISOString(),eta:new Date(now+300000).toISOString(),vehicle_ref:'v'+i,trip_id:'t'+i,location:{lat:32.09,lon:34.8}}))}};
const calls=[],p=createNationalProviders({now:()=>now,fetchImpl:async url=>{calls.push(url);if(url.endsWith('version.json'))return Response.json({version:'0123456789abcdef'});if(url.includes('catalog.json'))return Response.json(catalog);if(url.includes('curlbus.app'))return Response.json(source);const m=/line\/(5|18)\.json/.exec(url);if(m)return Response.json([{r:m[1]==='5'?'101':'102',a:15,d:0,c:[station,'30000'],x:shape,h:'יעד'}]);throw Error('unexpected '+url)}});
const data=await p.station(station);assert.equal(data.arrivals.length,2,'Every reported line at a national station is matched');assert.equal(data.vehicles.length,2);assert.equal(N.station(data,station,{now}).arrivals.length,2);assert.equal(N.station({...data,arrivals:[{...data.arrivals[0],operatorRef:3}]},station,{now}).arrivals.length,0);assert.throws(()=>N.station(data,'99999',{now}));
assert.equal(N.station({...data,sourceResponseAt:new Date(now+60000).toISOString()},station,{now}).vehicles.length,0,'Future source frame must clear its vehicles');
const old=global.fetch;let requests=0;global.fetch=async()=>{requests++;throw Error('should not fetch')};try{for(const [file,query]of [['national','kind=area&bbox=34,29,36,34'],['national','kind=station&stopCode=20000&url=https://bad.example'],['search','q=x'],['dataset','file=../secrets'],['dataset','file=version.json&url=https://bad.example']]){const {GET}=await import('../api/'+file+'.mjs');assert.equal((await GET(new Request('https://example.com/api/'+file+'?'+query))).status,400);}const {GET}=await import('../api/traffic.mjs');assert.equal((await GET(new Request('https://example.com/api/traffic?kind=status'))).status,200);assert.equal((await GET(new Request('https://example.com/api/traffic?z=14&x=1&y=1'))).status,503);assert.equal(requests,0)}finally{global.fetch=old}
console.log('PASS: national identity and clocks, future/archive rejection, all-line station matching, countrywide search, viewport isolation and bounded APIs');
})().catch(e=>{console.error(e);process.exitCode=1});
