/* Explicit address searches only. No background/autocomplete calls to the public geocoder. */
const cache=new Map(),pending=new Map();let last=0;
const out=(v,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'private, max-age=3600','X-Content-Type-Options':'nosniff'}});
export async function GET(request){const q=new URL(request.url).searchParams,text=(q.get('q')||'').trim();if(text.length<2||text.length>120||[...q.keys()].some(k=>k!=='q'||q.getAll(k).length!==1)||/[\x00-\x1f]/.test(text))return out({error:'INVALID_SEARCH'},400);
 const hit=cache.get(text);if(hit&&hit.until>Date.now())return out(hit.data);if(pending.has(text))return out(await pending.get(text));
 if(Date.now()-last<1100)return out({error:'SEARCH_BUSY'},429);last=Date.now();
 const task=(async()=>{const url=new URL('https://photon.komoot.io/api/');url.searchParams.set('q',text);url.searchParams.set('limit','6');url.searchParams.set('bbox','34,29,36,34');
  const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'EifoBatuach-DEV/9.1.6 (+https://github.com/j-h-h/abc)'},signal:AbortSignal.timeout(9000),redirect:'error'});if(!r.ok)throw Error('SEARCH_UNAVAILABLE');if(Number(r.headers.get('content-length')||0)>400000)throw Error('SEARCH_TOO_LARGE');const bytes=await r.arrayBuffer();if(bytes.byteLength>400000)throw Error('SEARCH_TOO_LARGE');const raw=JSON.parse(new TextDecoder().decode(bytes));if(!Array.isArray(raw.features))throw Error('INVALID_SEARCH_SOURCE');const places=raw.features.flatMap(f=>{const c=f.geometry?.coordinates,p=f.properties;if(f.geometry?.type!=='Point'||!p||!Array.isArray(c)||c.length!==2||!c.every(Number.isFinite)||c[0]<34||c[0]>36||c[1]<29||c[1]>34)return[];const label=[p.name,p.street&&p.street!==p.name?p.street:null,p.housenumber,p.city,p.state].filter(Boolean).join(' · ').slice(0,220);return label?[{name:label,lat:c[1],lon:c[0],type:p.osm_value||'place'}]:[]});const data={places,source:'Photon · OpenStreetMap'};if(cache.size>=200)cache.delete(cache.keys().next().value);cache.set(text,{data,until:Date.now()+86400000});return data;})();pending.set(text,task);try{return out(await task)}catch{return out({error:'SEARCH_UNAVAILABLE'},502)}finally{pending.delete(text)}
}
